#ifndef E2SM_HW_READER_H
#define E2SM_HW_READER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct hw_EventTriggerDefinitionFormat1_table *hw_EventTriggerDefinitionFormat1_table_t;
typedef struct hw_EventTriggerDefinitionFormat1_table *hw_EventTriggerDefinitionFormat1_mutable_table_t;
typedef const flatbuffers_uoffset_t *hw_EventTriggerDefinitionFormat1_vec_t;
typedef flatbuffers_uoffset_t *hw_EventTriggerDefinitionFormat1_mutable_vec_t;
typedef const struct hw_EventTrigger_table *hw_EventTrigger_table_t;
typedef struct hw_EventTrigger_table *hw_EventTrigger_mutable_table_t;
typedef const flatbuffers_uoffset_t *hw_EventTrigger_vec_t;
typedef flatbuffers_uoffset_t *hw_EventTrigger_mutable_vec_t;
typedef const struct hw_RanParameterItem_table *hw_RanParameterItem_table_t;
typedef struct hw_RanParameterItem_table *hw_RanParameterItem_mutable_table_t;
typedef const flatbuffers_uoffset_t *hw_RanParameterItem_vec_t;
typedef flatbuffers_uoffset_t *hw_RanParameterItem_mutable_vec_t;
typedef const struct hw_ActionDefinitionFormat1_table *hw_ActionDefinitionFormat1_table_t;
typedef struct hw_ActionDefinitionFormat1_table *hw_ActionDefinitionFormat1_mutable_table_t;
typedef const flatbuffers_uoffset_t *hw_ActionDefinitionFormat1_vec_t;
typedef flatbuffers_uoffset_t *hw_ActionDefinitionFormat1_mutable_vec_t;
typedef const struct hw_ActionDefinition_table *hw_ActionDefinition_table_t;
typedef struct hw_ActionDefinition_table *hw_ActionDefinition_mutable_table_t;
typedef const flatbuffers_uoffset_t *hw_ActionDefinition_vec_t;
typedef flatbuffers_uoffset_t *hw_ActionDefinition_mutable_vec_t;
typedef const struct hw_IndicationHeaderFormat1_table *hw_IndicationHeaderFormat1_table_t;
typedef struct hw_IndicationHeaderFormat1_table *hw_IndicationHeaderFormat1_mutable_table_t;
typedef const flatbuffers_uoffset_t *hw_IndicationHeaderFormat1_vec_t;
typedef flatbuffers_uoffset_t *hw_IndicationHeaderFormat1_mutable_vec_t;
typedef const struct hw_IndicationHeader_table *hw_IndicationHeader_table_t;
typedef struct hw_IndicationHeader_table *hw_IndicationHeader_mutable_table_t;
typedef const flatbuffers_uoffset_t *hw_IndicationHeader_vec_t;
typedef flatbuffers_uoffset_t *hw_IndicationHeader_mutable_vec_t;
typedef const struct hw_IndicationMessageFormat1_table *hw_IndicationMessageFormat1_table_t;
typedef struct hw_IndicationMessageFormat1_table *hw_IndicationMessageFormat1_mutable_table_t;
typedef const flatbuffers_uoffset_t *hw_IndicationMessageFormat1_vec_t;
typedef flatbuffers_uoffset_t *hw_IndicationMessageFormat1_mutable_vec_t;
typedef const struct hw_IndicationMessage_table *hw_IndicationMessage_table_t;
typedef struct hw_IndicationMessage_table *hw_IndicationMessage_mutable_table_t;
typedef const flatbuffers_uoffset_t *hw_IndicationMessage_vec_t;
typedef flatbuffers_uoffset_t *hw_IndicationMessage_mutable_vec_t;
typedef const struct hw_ControlHeaderFormat1_table *hw_ControlHeaderFormat1_table_t;
typedef struct hw_ControlHeaderFormat1_table *hw_ControlHeaderFormat1_mutable_table_t;
typedef const flatbuffers_uoffset_t *hw_ControlHeaderFormat1_vec_t;
typedef flatbuffers_uoffset_t *hw_ControlHeaderFormat1_mutable_vec_t;
typedef const struct hw_ControlHeader_table *hw_ControlHeader_table_t;
typedef struct hw_ControlHeader_table *hw_ControlHeader_mutable_table_t;
typedef const flatbuffers_uoffset_t *hw_ControlHeader_vec_t;
typedef flatbuffers_uoffset_t *hw_ControlHeader_mutable_vec_t;
typedef const struct hw_ControlMessageFormat1_table *hw_ControlMessageFormat1_table_t;
typedef struct hw_ControlMessageFormat1_table *hw_ControlMessageFormat1_mutable_table_t;
typedef const flatbuffers_uoffset_t *hw_ControlMessageFormat1_vec_t;
typedef flatbuffers_uoffset_t *hw_ControlMessageFormat1_mutable_vec_t;
typedef const struct hw_ControlMessage_table *hw_ControlMessage_table_t;
typedef struct hw_ControlMessage_table *hw_ControlMessage_mutable_table_t;
typedef const flatbuffers_uoffset_t *hw_ControlMessage_vec_t;
typedef flatbuffers_uoffset_t *hw_ControlMessage_mutable_vec_t;
#ifndef hw_EventTriggerDefinitionFormat1_file_identifier
#define hw_EventTriggerDefinitionFormat1_file_identifier flatbuffers_identifier
#endif
/* deprecated, use hw_EventTriggerDefinitionFormat1_file_identifier */
#ifndef hw_EventTriggerDefinitionFormat1_identifier
#define hw_EventTriggerDefinitionFormat1_identifier flatbuffers_identifier
#endif
#define hw_EventTriggerDefinitionFormat1_type_hash ((flatbuffers_thash_t)0x2ed18d73)
#define hw_EventTriggerDefinitionFormat1_type_identifier "\x73\x8d\xd1\x2e"
#ifndef hw_EventTrigger_file_identifier
#define hw_EventTrigger_file_identifier flatbuffers_identifier
#endif
/* deprecated, use hw_EventTrigger_file_identifier */
#ifndef hw_EventTrigger_identifier
#define hw_EventTrigger_identifier flatbuffers_identifier
#endif
#define hw_EventTrigger_type_hash ((flatbuffers_thash_t)0x35f808ae)
#define hw_EventTrigger_type_identifier "\xae\x08\xf8\x35"
#ifndef hw_RanParameterItem_file_identifier
#define hw_RanParameterItem_file_identifier flatbuffers_identifier
#endif
/* deprecated, use hw_RanParameterItem_file_identifier */
#ifndef hw_RanParameterItem_identifier
#define hw_RanParameterItem_identifier flatbuffers_identifier
#endif
#define hw_RanParameterItem_type_hash ((flatbuffers_thash_t)0xb533b49d)
#define hw_RanParameterItem_type_identifier "\x9d\xb4\x33\xb5"
#ifndef hw_ActionDefinitionFormat1_file_identifier
#define hw_ActionDefinitionFormat1_file_identifier flatbuffers_identifier
#endif
/* deprecated, use hw_ActionDefinitionFormat1_file_identifier */
#ifndef hw_ActionDefinitionFormat1_identifier
#define hw_ActionDefinitionFormat1_identifier flatbuffers_identifier
#endif
#define hw_ActionDefinitionFormat1_type_hash ((flatbuffers_thash_t)0x104acc15)
#define hw_ActionDefinitionFormat1_type_identifier "\x15\xcc\x4a\x10"
#ifndef hw_ActionDefinition_file_identifier
#define hw_ActionDefinition_file_identifier flatbuffers_identifier
#endif
/* deprecated, use hw_ActionDefinition_file_identifier */
#ifndef hw_ActionDefinition_identifier
#define hw_ActionDefinition_identifier flatbuffers_identifier
#endif
#define hw_ActionDefinition_type_hash ((flatbuffers_thash_t)0x69c53049)
#define hw_ActionDefinition_type_identifier "\x49\x30\xc5\x69"
#ifndef hw_IndicationHeaderFormat1_file_identifier
#define hw_IndicationHeaderFormat1_file_identifier flatbuffers_identifier
#endif
/* deprecated, use hw_IndicationHeaderFormat1_file_identifier */
#ifndef hw_IndicationHeaderFormat1_identifier
#define hw_IndicationHeaderFormat1_identifier flatbuffers_identifier
#endif
#define hw_IndicationHeaderFormat1_type_hash ((flatbuffers_thash_t)0xd12bbde5)
#define hw_IndicationHeaderFormat1_type_identifier "\xe5\xbd\x2b\xd1"
#ifndef hw_IndicationHeader_file_identifier
#define hw_IndicationHeader_file_identifier flatbuffers_identifier
#endif
/* deprecated, use hw_IndicationHeader_file_identifier */
#ifndef hw_IndicationHeader_identifier
#define hw_IndicationHeader_identifier flatbuffers_identifier
#endif
#define hw_IndicationHeader_type_hash ((flatbuffers_thash_t)0xfa05abd9)
#define hw_IndicationHeader_type_identifier "\xd9\xab\x05\xfa"
#ifndef hw_IndicationMessageFormat1_file_identifier
#define hw_IndicationMessageFormat1_file_identifier flatbuffers_identifier
#endif
/* deprecated, use hw_IndicationMessageFormat1_file_identifier */
#ifndef hw_IndicationMessageFormat1_identifier
#define hw_IndicationMessageFormat1_identifier flatbuffers_identifier
#endif
#define hw_IndicationMessageFormat1_type_hash ((flatbuffers_thash_t)0xc3e279bf)
#define hw_IndicationMessageFormat1_type_identifier "\xbf\x79\xe2\xc3"
#ifndef hw_IndicationMessage_file_identifier
#define hw_IndicationMessage_file_identifier flatbuffers_identifier
#endif
/* deprecated, use hw_IndicationMessage_file_identifier */
#ifndef hw_IndicationMessage_identifier
#define hw_IndicationMessage_identifier flatbuffers_identifier
#endif
#define hw_IndicationMessage_type_hash ((flatbuffers_thash_t)0x682b3cb)
#define hw_IndicationMessage_type_identifier "\xcb\xb3\x82\x06"
#ifndef hw_ControlHeaderFormat1_file_identifier
#define hw_ControlHeaderFormat1_file_identifier flatbuffers_identifier
#endif
/* deprecated, use hw_ControlHeaderFormat1_file_identifier */
#ifndef hw_ControlHeaderFormat1_identifier
#define hw_ControlHeaderFormat1_identifier flatbuffers_identifier
#endif
#define hw_ControlHeaderFormat1_type_hash ((flatbuffers_thash_t)0x8b53f72c)
#define hw_ControlHeaderFormat1_type_identifier "\x2c\xf7\x53\x8b"
#ifndef hw_ControlHeader_file_identifier
#define hw_ControlHeader_file_identifier flatbuffers_identifier
#endif
/* deprecated, use hw_ControlHeader_file_identifier */
#ifndef hw_ControlHeader_identifier
#define hw_ControlHeader_identifier flatbuffers_identifier
#endif
#define hw_ControlHeader_type_hash ((flatbuffers_thash_t)0x14662366)
#define hw_ControlHeader_type_identifier "\x66\x23\x66\x14"
#ifndef hw_ControlMessageFormat1_file_identifier
#define hw_ControlMessageFormat1_file_identifier flatbuffers_identifier
#endif
/* deprecated, use hw_ControlMessageFormat1_file_identifier */
#ifndef hw_ControlMessageFormat1_identifier
#define hw_ControlMessageFormat1_identifier flatbuffers_identifier
#endif
#define hw_ControlMessageFormat1_type_hash ((flatbuffers_thash_t)0x3b6b40e4)
#define hw_ControlMessageFormat1_type_identifier "\xe4\x40\x6b\x3b"
#ifndef hw_ControlMessage_file_identifier
#define hw_ControlMessage_file_identifier flatbuffers_identifier
#endif
/* deprecated, use hw_ControlMessage_file_identifier */
#ifndef hw_ControlMessage_identifier
#define hw_ControlMessage_identifier flatbuffers_identifier
#endif
#define hw_ControlMessage_type_hash ((flatbuffers_thash_t)0xb8c8042e)
#define hw_ControlMessage_type_identifier "\x2e\x04\xc8\xb8"

typedef uint8_t hw_TriggerNature_enum_t;
__flatbuffers_define_integer_type(hw_TriggerNature, hw_TriggerNature_enum_t, 8)
#define hw_TriggerNature_Now ((hw_TriggerNature_enum_t)UINT8_C(0))
#define hw_TriggerNature_OnChange ((hw_TriggerNature_enum_t)UINT8_C(1))

static inline const char *hw_TriggerNature_name(hw_TriggerNature_enum_t value)
{
    switch (value) {
    case hw_TriggerNature_Now: return "Now";
    case hw_TriggerNature_OnChange: return "OnChange";
    default: return "";
    }
}

static inline int hw_TriggerNature_is_known_value(hw_TriggerNature_enum_t value)
{
    switch (value) {
    case hw_TriggerNature_Now: return 1;
    case hw_TriggerNature_OnChange: return 1;
    default: return 0;
    }
}

typedef uint8_t hw_RanParameterTest_enum_t;
__flatbuffers_define_integer_type(hw_RanParameterTest, hw_RanParameterTest_enum_t, 8)
#define hw_RanParameterTest_equal ((hw_RanParameterTest_enum_t)UINT8_C(0))
#define hw_RanParameterTest_greaterThan ((hw_RanParameterTest_enum_t)UINT8_C(1))
#define hw_RanParameterTest_lessThan ((hw_RanParameterTest_enum_t)UINT8_C(2))
#define hw_RanParameterTest_contains ((hw_RanParameterTest_enum_t)UINT8_C(3))
#define hw_RanParameterTest_present ((hw_RanParameterTest_enum_t)UINT8_C(4))

static inline const char *hw_RanParameterTest_name(hw_RanParameterTest_enum_t value)
{
    switch (value) {
    case hw_RanParameterTest_equal: return "equal";
    case hw_RanParameterTest_greaterThan: return "greaterThan";
    case hw_RanParameterTest_lessThan: return "lessThan";
    case hw_RanParameterTest_contains: return "contains";
    case hw_RanParameterTest_present: return "present";
    default: return "";
    }
}

static inline int hw_RanParameterTest_is_known_value(hw_RanParameterTest_enum_t value)
{
    switch (value) {
    case hw_RanParameterTest_equal: return 1;
    case hw_RanParameterTest_greaterThan: return 1;
    case hw_RanParameterTest_lessThan: return 1;
    case hw_RanParameterTest_contains: return 1;
    case hw_RanParameterTest_present: return 1;
    default: return 0;
    }
}



struct hw_EventTriggerDefinitionFormat1_table { uint8_t unused__; };

static inline size_t hw_EventTriggerDefinitionFormat1_vec_len(hw_EventTriggerDefinitionFormat1_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hw_EventTriggerDefinitionFormat1_table_t hw_EventTriggerDefinitionFormat1_vec_at(hw_EventTriggerDefinitionFormat1_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hw_EventTriggerDefinitionFormat1_table_t, vec, i, 0)
__flatbuffers_table_as_root(hw_EventTriggerDefinitionFormat1)

__flatbuffers_define_scalar_field(0, hw_EventTriggerDefinitionFormat1, triggerNature, hw_TriggerNature, hw_TriggerNature_enum_t, UINT8_C(0))
typedef uint8_t hw_EventTriggerUnion_union_type_t;
__flatbuffers_define_integer_type(hw_EventTriggerUnion, hw_EventTriggerUnion_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, hw_EventTriggerUnion)
#define hw_EventTriggerUnion_NONE ((hw_EventTriggerUnion_union_type_t)UINT8_C(0))
#define hw_EventTriggerUnion_eventDefF1 ((hw_EventTriggerUnion_union_type_t)UINT8_C(1))

static inline const char *hw_EventTriggerUnion_type_name(hw_EventTriggerUnion_union_type_t type)
{
    switch (type) {
    case hw_EventTriggerUnion_NONE: return "NONE";
    case hw_EventTriggerUnion_eventDefF1: return "eventDefF1";
    default: return "";
    }
}

static inline int hw_EventTriggerUnion_is_known_type(hw_EventTriggerUnion_union_type_t type)
{
    switch (type) {
    case hw_EventTriggerUnion_NONE: return 1;
    case hw_EventTriggerUnion_eventDefF1: return 1;
    default: return 0;
    }
}


struct hw_EventTrigger_table { uint8_t unused__; };

static inline size_t hw_EventTrigger_vec_len(hw_EventTrigger_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hw_EventTrigger_table_t hw_EventTrigger_vec_at(hw_EventTrigger_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hw_EventTrigger_table_t, vec, i, 0)
__flatbuffers_table_as_root(hw_EventTrigger)

__flatbuffers_define_union_field(flatbuffers_, 1, hw_EventTrigger, trig, hw_EventTriggerUnion, 0)

struct hw_RanParameterItem_table { uint8_t unused__; };

static inline size_t hw_RanParameterItem_vec_len(hw_RanParameterItem_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hw_RanParameterItem_table_t hw_RanParameterItem_vec_at(hw_RanParameterItem_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hw_RanParameterItem_table_t, vec, i, 0)
__flatbuffers_table_as_root(hw_RanParameterItem)

__flatbuffers_define_scalar_field(0, hw_RanParameterItem, id, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_string_field(1, hw_RanParameterItem, name, 0)
__flatbuffers_define_scalar_field(2, hw_RanParameterItem, test, hw_RanParameterTest, hw_RanParameterTest_enum_t, UINT8_C(0))
__flatbuffers_define_string_field(3, hw_RanParameterItem, value, 0)

struct hw_ActionDefinitionFormat1_table { uint8_t unused__; };

static inline size_t hw_ActionDefinitionFormat1_vec_len(hw_ActionDefinitionFormat1_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hw_ActionDefinitionFormat1_table_t hw_ActionDefinitionFormat1_vec_at(hw_ActionDefinitionFormat1_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hw_ActionDefinitionFormat1_table_t, vec, i, 0)
__flatbuffers_table_as_root(hw_ActionDefinitionFormat1)

__flatbuffers_define_vector_field(0, hw_ActionDefinitionFormat1, ranParameterList, hw_RanParameterItem_vec_t, 0)
typedef uint8_t hw_ActionDefinitionUnion_union_type_t;
__flatbuffers_define_integer_type(hw_ActionDefinitionUnion, hw_ActionDefinitionUnion_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, hw_ActionDefinitionUnion)
#define hw_ActionDefinitionUnion_NONE ((hw_ActionDefinitionUnion_union_type_t)UINT8_C(0))
#define hw_ActionDefinitionUnion_actionDefF1 ((hw_ActionDefinitionUnion_union_type_t)UINT8_C(1))

static inline const char *hw_ActionDefinitionUnion_type_name(hw_ActionDefinitionUnion_union_type_t type)
{
    switch (type) {
    case hw_ActionDefinitionUnion_NONE: return "NONE";
    case hw_ActionDefinitionUnion_actionDefF1: return "actionDefF1";
    default: return "";
    }
}

static inline int hw_ActionDefinitionUnion_is_known_type(hw_ActionDefinitionUnion_union_type_t type)
{
    switch (type) {
    case hw_ActionDefinitionUnion_NONE: return 1;
    case hw_ActionDefinitionUnion_actionDefF1: return 1;
    default: return 0;
    }
}


struct hw_ActionDefinition_table { uint8_t unused__; };

static inline size_t hw_ActionDefinition_vec_len(hw_ActionDefinition_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hw_ActionDefinition_table_t hw_ActionDefinition_vec_at(hw_ActionDefinition_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hw_ActionDefinition_table_t, vec, i, 0)
__flatbuffers_table_as_root(hw_ActionDefinition)

__flatbuffers_define_union_field(flatbuffers_, 1, hw_ActionDefinition, def, hw_ActionDefinitionUnion, 0)

struct hw_IndicationHeaderFormat1_table { uint8_t unused__; };

static inline size_t hw_IndicationHeaderFormat1_vec_len(hw_IndicationHeaderFormat1_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hw_IndicationHeaderFormat1_table_t hw_IndicationHeaderFormat1_vec_at(hw_IndicationHeaderFormat1_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hw_IndicationHeaderFormat1_table_t, vec, i, 0)
__flatbuffers_table_as_root(hw_IndicationHeaderFormat1)

__flatbuffers_define_scalar_field(0, hw_IndicationHeaderFormat1, param, flatbuffers_uint32, uint32_t, UINT32_C(0))
typedef uint8_t hw_IndicationHeaderUnion_union_type_t;
__flatbuffers_define_integer_type(hw_IndicationHeaderUnion, hw_IndicationHeaderUnion_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, hw_IndicationHeaderUnion)
#define hw_IndicationHeaderUnion_NONE ((hw_IndicationHeaderUnion_union_type_t)UINT8_C(0))
#define hw_IndicationHeaderUnion_indHeaderF1 ((hw_IndicationHeaderUnion_union_type_t)UINT8_C(1))

static inline const char *hw_IndicationHeaderUnion_type_name(hw_IndicationHeaderUnion_union_type_t type)
{
    switch (type) {
    case hw_IndicationHeaderUnion_NONE: return "NONE";
    case hw_IndicationHeaderUnion_indHeaderF1: return "indHeaderF1";
    default: return "";
    }
}

static inline int hw_IndicationHeaderUnion_is_known_type(hw_IndicationHeaderUnion_union_type_t type)
{
    switch (type) {
    case hw_IndicationHeaderUnion_NONE: return 1;
    case hw_IndicationHeaderUnion_indHeaderF1: return 1;
    default: return 0;
    }
}


struct hw_IndicationHeader_table { uint8_t unused__; };

static inline size_t hw_IndicationHeader_vec_len(hw_IndicationHeader_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hw_IndicationHeader_table_t hw_IndicationHeader_vec_at(hw_IndicationHeader_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hw_IndicationHeader_table_t, vec, i, 0)
__flatbuffers_table_as_root(hw_IndicationHeader)

__flatbuffers_define_union_field(flatbuffers_, 1, hw_IndicationHeader, hdr, hw_IndicationHeaderUnion, 0)

struct hw_IndicationMessageFormat1_table { uint8_t unused__; };

static inline size_t hw_IndicationMessageFormat1_vec_len(hw_IndicationMessageFormat1_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hw_IndicationMessageFormat1_table_t hw_IndicationMessageFormat1_vec_at(hw_IndicationMessageFormat1_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hw_IndicationMessageFormat1_table_t, vec, i, 0)
__flatbuffers_table_as_root(hw_IndicationMessageFormat1)

__flatbuffers_define_vector_field(0, hw_IndicationMessageFormat1, param, flatbuffers_uint8_vec_t, 0)
typedef uint8_t hw_IndicationMessageUnion_union_type_t;
__flatbuffers_define_integer_type(hw_IndicationMessageUnion, hw_IndicationMessageUnion_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, hw_IndicationMessageUnion)
#define hw_IndicationMessageUnion_NONE ((hw_IndicationMessageUnion_union_type_t)UINT8_C(0))
#define hw_IndicationMessageUnion_indMessageF1 ((hw_IndicationMessageUnion_union_type_t)UINT8_C(1))

static inline const char *hw_IndicationMessageUnion_type_name(hw_IndicationMessageUnion_union_type_t type)
{
    switch (type) {
    case hw_IndicationMessageUnion_NONE: return "NONE";
    case hw_IndicationMessageUnion_indMessageF1: return "indMessageF1";
    default: return "";
    }
}

static inline int hw_IndicationMessageUnion_is_known_type(hw_IndicationMessageUnion_union_type_t type)
{
    switch (type) {
    case hw_IndicationMessageUnion_NONE: return 1;
    case hw_IndicationMessageUnion_indMessageF1: return 1;
    default: return 0;
    }
}


struct hw_IndicationMessage_table { uint8_t unused__; };

static inline size_t hw_IndicationMessage_vec_len(hw_IndicationMessage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hw_IndicationMessage_table_t hw_IndicationMessage_vec_at(hw_IndicationMessage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hw_IndicationMessage_table_t, vec, i, 0)
__flatbuffers_table_as_root(hw_IndicationMessage)

__flatbuffers_define_union_field(flatbuffers_, 1, hw_IndicationMessage, msg, hw_IndicationMessageUnion, 0)

struct hw_ControlHeaderFormat1_table { uint8_t unused__; };

static inline size_t hw_ControlHeaderFormat1_vec_len(hw_ControlHeaderFormat1_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hw_ControlHeaderFormat1_table_t hw_ControlHeaderFormat1_vec_at(hw_ControlHeaderFormat1_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hw_ControlHeaderFormat1_table_t, vec, i, 0)
__flatbuffers_table_as_root(hw_ControlHeaderFormat1)

__flatbuffers_define_scalar_field(0, hw_ControlHeaderFormat1, param, flatbuffers_uint32, uint32_t, UINT32_C(0))
typedef uint8_t hw_ControlHeaderUnion_union_type_t;
__flatbuffers_define_integer_type(hw_ControlHeaderUnion, hw_ControlHeaderUnion_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, hw_ControlHeaderUnion)
#define hw_ControlHeaderUnion_NONE ((hw_ControlHeaderUnion_union_type_t)UINT8_C(0))
#define hw_ControlHeaderUnion_ctrlHeaderF1 ((hw_ControlHeaderUnion_union_type_t)UINT8_C(1))

static inline const char *hw_ControlHeaderUnion_type_name(hw_ControlHeaderUnion_union_type_t type)
{
    switch (type) {
    case hw_ControlHeaderUnion_NONE: return "NONE";
    case hw_ControlHeaderUnion_ctrlHeaderF1: return "ctrlHeaderF1";
    default: return "";
    }
}

static inline int hw_ControlHeaderUnion_is_known_type(hw_ControlHeaderUnion_union_type_t type)
{
    switch (type) {
    case hw_ControlHeaderUnion_NONE: return 1;
    case hw_ControlHeaderUnion_ctrlHeaderF1: return 1;
    default: return 0;
    }
}


struct hw_ControlHeader_table { uint8_t unused__; };

static inline size_t hw_ControlHeader_vec_len(hw_ControlHeader_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hw_ControlHeader_table_t hw_ControlHeader_vec_at(hw_ControlHeader_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hw_ControlHeader_table_t, vec, i, 0)
__flatbuffers_table_as_root(hw_ControlHeader)

__flatbuffers_define_union_field(flatbuffers_, 1, hw_ControlHeader, hdr, hw_ControlHeaderUnion, 0)

struct hw_ControlMessageFormat1_table { uint8_t unused__; };

static inline size_t hw_ControlMessageFormat1_vec_len(hw_ControlMessageFormat1_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hw_ControlMessageFormat1_table_t hw_ControlMessageFormat1_vec_at(hw_ControlMessageFormat1_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hw_ControlMessageFormat1_table_t, vec, i, 0)
__flatbuffers_table_as_root(hw_ControlMessageFormat1)

__flatbuffers_define_vector_field(0, hw_ControlMessageFormat1, param, flatbuffers_uint8_vec_t, 0)
typedef uint8_t hw_ControlMessageUnion_union_type_t;
__flatbuffers_define_integer_type(hw_ControlMessageUnion, hw_ControlMessageUnion_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, hw_ControlMessageUnion)
#define hw_ControlMessageUnion_NONE ((hw_ControlMessageUnion_union_type_t)UINT8_C(0))
#define hw_ControlMessageUnion_ctrlMessageF1 ((hw_ControlMessageUnion_union_type_t)UINT8_C(1))

static inline const char *hw_ControlMessageUnion_type_name(hw_ControlMessageUnion_union_type_t type)
{
    switch (type) {
    case hw_ControlMessageUnion_NONE: return "NONE";
    case hw_ControlMessageUnion_ctrlMessageF1: return "ctrlMessageF1";
    default: return "";
    }
}

static inline int hw_ControlMessageUnion_is_known_type(hw_ControlMessageUnion_union_type_t type)
{
    switch (type) {
    case hw_ControlMessageUnion_NONE: return 1;
    case hw_ControlMessageUnion_ctrlMessageF1: return 1;
    default: return 0;
    }
}


struct hw_ControlMessage_table { uint8_t unused__; };

static inline size_t hw_ControlMessage_vec_len(hw_ControlMessage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hw_ControlMessage_table_t hw_ControlMessage_vec_at(hw_ControlMessage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hw_ControlMessage_table_t, vec, i, 0)
__flatbuffers_table_as_root(hw_ControlMessage)

__flatbuffers_define_union_field(flatbuffers_, 1, hw_ControlMessage, msg, hw_ControlMessageUnion, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* E2SM_HW_READER_H */
