#ifndef MAC_STATS_JSON_PRINTER_H
#define MAC_STATS_JSON_PRINTER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#include "flatcc/flatcc_json_printer.h"
#include "flatcc/flatcc_prologue.h"

static void mac_stats_EventTrigger_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void mac_stats_ReportStyle_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void mac_stats_ActionDefinition_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void mac_stats_IndicationHeader_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void mac_stats_bsrStat_print_json_struct(flatcc_json_printer_t *ctx, const void *p);
static void mac_stats_UEStats_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void mac_stats_IndicationMessage_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void mac_stats_RanFunctionDefinition_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);

static void mac_stats_ReportStyleType_print_json_enum(flatcc_json_printer_t *ctx, uint8_t v)
{

    switch (v) {
    case 0: flatcc_json_printer_enum(ctx, "Minimal", 7); break;
    case 1: flatcc_json_printer_enum(ctx, "Complete", 8); break;
    default: flatcc_json_printer_uint8(ctx, v); break;
    }
}

static void mac_stats_bsrStat_print_json_struct(flatcc_json_printer_t *ctx, const void *p)
{
    flatcc_json_printer_uint8_struct_field(ctx, 0, p, 0, "lcgid", 5);
    flatcc_json_printer_uint32_struct_field(ctx, 1, p, 4, "bufferSize", 10);
}

static inline int mac_stats_bsrStat_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_struct_as_root(ctx, buf, bufsiz, fid, mac_stats_bsrStat_print_json_struct);
}

static void mac_stats_EventTrigger_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_uint16_field(ctx, td, 0, "msReportPeriod", 14, 0);
}

static inline int mac_stats_EventTrigger_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, mac_stats_EventTrigger_print_json_table);
}

static void mac_stats_ReportStyle_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_uint8_enum_field(ctx, td, 0, "type", 4, 0, mac_stats_ReportStyleType_print_json_enum);
}

static inline int mac_stats_ReportStyle_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, mac_stats_ReportStyle_print_json_table);
}

static void mac_stats_ActionDefinition_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_table_field(ctx, td, 0, "reportStyle", 11, mac_stats_ReportStyle_print_json_table);
}

static inline int mac_stats_ActionDefinition_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, mac_stats_ActionDefinition_print_json_table);
}

static void mac_stats_IndicationHeader_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_uint16_field(ctx, td, 0, "frame", 5, 0);
    flatcc_json_printer_uint8_field(ctx, td, 1, "slot", 4, 0);
}

static inline int mac_stats_IndicationHeader_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, mac_stats_IndicationHeader_print_json_table);
}

static void mac_stats_UEStats_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_uint16_field(ctx, td, 0, "rnti", 4, 0);
    flatcc_json_printer_uint32_field(ctx, td, 1, "dlAggrPrb", 9, 0);
    flatcc_json_printer_uint32_field(ctx, td, 2, "ulAggrPrb", 9, 0);
    flatcc_json_printer_uint64_field(ctx, td, 3, "dlAggrTbs", 9, 0);
    flatcc_json_printer_uint64_field(ctx, td, 4, "ulAggrTbs", 9, 0);
    flatcc_json_printer_uint32_field(ctx, td, 5, "dlAggrSdus", 10, 0);
    flatcc_json_printer_uint32_field(ctx, td, 6, "ulAggrSdus", 10, 0);
    flatcc_json_printer_uint64_field(ctx, td, 7, "dlAggrBytesSdus", 15, 0);
    flatcc_json_printer_uint64_field(ctx, td, 8, "ulAggrBytesSdus", 15, 0);
    flatcc_json_printer_uint32_field(ctx, td, 9, "dlAggrRetxPrb", 13, 0);
    flatcc_json_printer_uint32_field(ctx, td, 10, "ulAggrRetxPrb", 13, 0);
    flatcc_json_printer_uint8_field(ctx, td, 11, "wbCqi", 5, 0);
    flatcc_json_printer_uint8_field(ctx, td, 12, "dlMcs1", 6, 0);
    flatcc_json_printer_uint8_field(ctx, td, 13, "ulMcs1", 6, 0);
    flatcc_json_printer_uint8_field(ctx, td, 14, "dlMcs2", 6, 0);
    flatcc_json_printer_uint8_field(ctx, td, 15, "ulMcs2", 6, 0);
    flatcc_json_printer_float_field(ctx, td, 16, "puschSnr", 8, -64.000000);
    flatcc_json_printer_float_field(ctx, td, 17, "pucchSnr", 8, -64.000000);
    flatcc_json_printer_int8_field(ctx, td, 18, "phr", 3, 0);
    flatcc_json_printer_struct_vector_field(ctx, td, 19, "bsr", 3, 8, mac_stats_bsrStat_print_json_struct);
    flatcc_json_printer_uint32_vector_field(ctx, td, 20, "dlHarq", 6);
    flatcc_json_printer_uint32_vector_field(ctx, td, 21, "ulHarq", 6);
}

static inline int mac_stats_UEStats_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, mac_stats_UEStats_print_json_table);
}

static void mac_stats_IndicationMessage_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_table_vector_field(ctx, td, 0, "ueStats", 7, mac_stats_UEStats_print_json_table);
}

static inline int mac_stats_IndicationMessage_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, mac_stats_IndicationMessage_print_json_table);
}

static void mac_stats_RanFunctionDefinition_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_table_vector_field(ctx, td, 0, "supportedReportStyles", 21, mac_stats_ReportStyle_print_json_table);
}

static inline int mac_stats_RanFunctionDefinition_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, mac_stats_RanFunctionDefinition_print_json_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* MAC_STATS_JSON_PRINTER_H */
