#ifndef MAC_STATS_VERIFIER_H
#define MAC_STATS_VERIFIER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef MAC_STATS_READER_H
#include "mac_stats_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int mac_stats_EventTrigger_verify_table(flatcc_table_verifier_descriptor_t *td);
static int mac_stats_ReportStyle_verify_table(flatcc_table_verifier_descriptor_t *td);
static int mac_stats_ActionDefinition_verify_table(flatcc_table_verifier_descriptor_t *td);
static int mac_stats_IndicationHeader_verify_table(flatcc_table_verifier_descriptor_t *td);
static int mac_stats_UEStats_verify_table(flatcc_table_verifier_descriptor_t *td);
static int mac_stats_IndicationMessage_verify_table(flatcc_table_verifier_descriptor_t *td);
static int mac_stats_RanFunctionDefinition_verify_table(flatcc_table_verifier_descriptor_t *td);

static inline int mac_stats_bsrStat_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, mac_stats_bsrStat_identifier, 8, 4);
}

static inline int mac_stats_bsrStat_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, mac_stats_bsrStat_type_hash, 8, 4);
}

static inline int mac_stats_bsrStat_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 4);
}

static inline int mac_stats_bsrStat_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 4);
}

static int mac_stats_EventTrigger_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* msReportPeriod */)) return ret;
    return flatcc_verify_ok;
}

static inline int mac_stats_EventTrigger_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, mac_stats_EventTrigger_identifier, &mac_stats_EventTrigger_verify_table);
}

static inline int mac_stats_EventTrigger_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, mac_stats_EventTrigger_type_identifier, &mac_stats_EventTrigger_verify_table);
}

static inline int mac_stats_EventTrigger_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &mac_stats_EventTrigger_verify_table);
}

static inline int mac_stats_EventTrigger_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &mac_stats_EventTrigger_verify_table);
}

static int mac_stats_ReportStyle_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* type */)) return ret;
    return flatcc_verify_ok;
}

static inline int mac_stats_ReportStyle_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, mac_stats_ReportStyle_identifier, &mac_stats_ReportStyle_verify_table);
}

static inline int mac_stats_ReportStyle_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, mac_stats_ReportStyle_type_identifier, &mac_stats_ReportStyle_verify_table);
}

static inline int mac_stats_ReportStyle_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &mac_stats_ReportStyle_verify_table);
}

static inline int mac_stats_ReportStyle_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &mac_stats_ReportStyle_verify_table);
}

static int mac_stats_ActionDefinition_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_field(td, 0, 0, &mac_stats_ReportStyle_verify_table) /* reportStyle */)) return ret;
    return flatcc_verify_ok;
}

static inline int mac_stats_ActionDefinition_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, mac_stats_ActionDefinition_identifier, &mac_stats_ActionDefinition_verify_table);
}

static inline int mac_stats_ActionDefinition_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, mac_stats_ActionDefinition_type_identifier, &mac_stats_ActionDefinition_verify_table);
}

static inline int mac_stats_ActionDefinition_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &mac_stats_ActionDefinition_verify_table);
}

static inline int mac_stats_ActionDefinition_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &mac_stats_ActionDefinition_verify_table);
}

static int mac_stats_IndicationHeader_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* frame */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 1, 1) /* slot */)) return ret;
    return flatcc_verify_ok;
}

static inline int mac_stats_IndicationHeader_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, mac_stats_IndicationHeader_identifier, &mac_stats_IndicationHeader_verify_table);
}

static inline int mac_stats_IndicationHeader_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, mac_stats_IndicationHeader_type_identifier, &mac_stats_IndicationHeader_verify_table);
}

static inline int mac_stats_IndicationHeader_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &mac_stats_IndicationHeader_verify_table);
}

static inline int mac_stats_IndicationHeader_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &mac_stats_IndicationHeader_verify_table);
}

static int mac_stats_UEStats_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* rnti */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* dlAggrPrb */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* ulAggrPrb */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 8, 8) /* dlAggrTbs */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 8, 8) /* ulAggrTbs */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 4, 4) /* dlAggrSdus */)) return ret;
    if ((ret = flatcc_verify_field(td, 6, 4, 4) /* ulAggrSdus */)) return ret;
    if ((ret = flatcc_verify_field(td, 7, 8, 8) /* dlAggrBytesSdus */)) return ret;
    if ((ret = flatcc_verify_field(td, 8, 8, 8) /* ulAggrBytesSdus */)) return ret;
    if ((ret = flatcc_verify_field(td, 9, 4, 4) /* dlAggrRetxPrb */)) return ret;
    if ((ret = flatcc_verify_field(td, 10, 4, 4) /* ulAggrRetxPrb */)) return ret;
    if ((ret = flatcc_verify_field(td, 11, 1, 1) /* wbCqi */)) return ret;
    if ((ret = flatcc_verify_field(td, 12, 1, 1) /* dlMcs1 */)) return ret;
    if ((ret = flatcc_verify_field(td, 13, 1, 1) /* ulMcs1 */)) return ret;
    if ((ret = flatcc_verify_field(td, 14, 1, 1) /* dlMcs2 */)) return ret;
    if ((ret = flatcc_verify_field(td, 15, 1, 1) /* ulMcs2 */)) return ret;
    if ((ret = flatcc_verify_field(td, 16, 4, 4) /* puschSnr */)) return ret;
    if ((ret = flatcc_verify_field(td, 17, 4, 4) /* pucchSnr */)) return ret;
    if ((ret = flatcc_verify_field(td, 18, 1, 1) /* phr */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 19, 0, 8, 4, INT64_C(536870911)) /* bsr */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 20, 0, 4, 4, INT64_C(1073741823)) /* dlHarq */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 21, 0, 4, 4, INT64_C(1073741823)) /* ulHarq */)) return ret;
    return flatcc_verify_ok;
}

static inline int mac_stats_UEStats_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, mac_stats_UEStats_identifier, &mac_stats_UEStats_verify_table);
}

static inline int mac_stats_UEStats_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, mac_stats_UEStats_type_identifier, &mac_stats_UEStats_verify_table);
}

static inline int mac_stats_UEStats_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &mac_stats_UEStats_verify_table);
}

static inline int mac_stats_UEStats_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &mac_stats_UEStats_verify_table);
}

static int mac_stats_IndicationMessage_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &mac_stats_UEStats_verify_table) /* ueStats */)) return ret;
    return flatcc_verify_ok;
}

static inline int mac_stats_IndicationMessage_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, mac_stats_IndicationMessage_identifier, &mac_stats_IndicationMessage_verify_table);
}

static inline int mac_stats_IndicationMessage_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, mac_stats_IndicationMessage_type_identifier, &mac_stats_IndicationMessage_verify_table);
}

static inline int mac_stats_IndicationMessage_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &mac_stats_IndicationMessage_verify_table);
}

static inline int mac_stats_IndicationMessage_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &mac_stats_IndicationMessage_verify_table);
}

static int mac_stats_RanFunctionDefinition_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &mac_stats_ReportStyle_verify_table) /* supportedReportStyles */)) return ret;
    return flatcc_verify_ok;
}

static inline int mac_stats_RanFunctionDefinition_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, mac_stats_RanFunctionDefinition_identifier, &mac_stats_RanFunctionDefinition_verify_table);
}

static inline int mac_stats_RanFunctionDefinition_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, mac_stats_RanFunctionDefinition_type_identifier, &mac_stats_RanFunctionDefinition_verify_table);
}

static inline int mac_stats_RanFunctionDefinition_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &mac_stats_RanFunctionDefinition_verify_table);
}

static inline int mac_stats_RanFunctionDefinition_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &mac_stats_RanFunctionDefinition_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* MAC_STATS_VERIFIER_H */
