#ifndef RRC_STATS_VERIFIER_H
#define RRC_STATS_VERIFIER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef RRC_STATS_READER_H
#include "rrc_stats_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#ifndef RRC_COMMON_VERIFIER_H
#include "rrc_common_verifier.h"
#endif
#include "flatcc/flatcc_prologue.h"

static int rrc_stats_EventTrigger_verify_table(flatcc_table_verifier_descriptor_t *td);
static int rrc_stats_ReportStyle_verify_table(flatcc_table_verifier_descriptor_t *td);
static int rrc_stats_ActionDefinition_verify_table(flatcc_table_verifier_descriptor_t *td);
static int rrc_stats_IndicationHeader_verify_table(flatcc_table_verifier_descriptor_t *td);
static int rrc_stats_MeasResult_verify_table(flatcc_table_verifier_descriptor_t *td);
static int rrc_stats_NeighMeas_verify_table(flatcc_table_verifier_descriptor_t *td);
static int rrc_stats_MeasReport_verify_table(flatcc_table_verifier_descriptor_t *td);
static int rrc_stats_IndicationMessage_verify_table(flatcc_table_verifier_descriptor_t *td);
static int rrc_stats_RanFunctionDefinition_verify_table(flatcc_table_verifier_descriptor_t *td);

static int rrc_stats_EventTrigger_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* reportOccasion */)) return ret;
    return flatcc_verify_ok;
}

static inline int rrc_stats_EventTrigger_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_EventTrigger_identifier, &rrc_stats_EventTrigger_verify_table);
}

static inline int rrc_stats_EventTrigger_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_EventTrigger_type_identifier, &rrc_stats_EventTrigger_verify_table);
}

static inline int rrc_stats_EventTrigger_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &rrc_stats_EventTrigger_verify_table);
}

static inline int rrc_stats_EventTrigger_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &rrc_stats_EventTrigger_verify_table);
}

static int rrc_stats_ReportStyle_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* type */)) return ret;
    return flatcc_verify_ok;
}

static inline int rrc_stats_ReportStyle_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_ReportStyle_identifier, &rrc_stats_ReportStyle_verify_table);
}

static inline int rrc_stats_ReportStyle_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_ReportStyle_type_identifier, &rrc_stats_ReportStyle_verify_table);
}

static inline int rrc_stats_ReportStyle_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &rrc_stats_ReportStyle_verify_table);
}

static inline int rrc_stats_ReportStyle_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &rrc_stats_ReportStyle_verify_table);
}

static int rrc_stats_ActionDefinition_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_field(td, 0, 0, &rrc_stats_ReportStyle_verify_table) /* reportStyle */)) return ret;
    return flatcc_verify_ok;
}

static inline int rrc_stats_ActionDefinition_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_ActionDefinition_identifier, &rrc_stats_ActionDefinition_verify_table);
}

static inline int rrc_stats_ActionDefinition_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_ActionDefinition_type_identifier, &rrc_stats_ActionDefinition_verify_table);
}

static inline int rrc_stats_ActionDefinition_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &rrc_stats_ActionDefinition_verify_table);
}

static inline int rrc_stats_ActionDefinition_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &rrc_stats_ActionDefinition_verify_table);
}

static int rrc_stats_IndicationHeader_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* rnti */)) return ret;
    return flatcc_verify_ok;
}

static inline int rrc_stats_IndicationHeader_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_IndicationHeader_identifier, &rrc_stats_IndicationHeader_verify_table);
}

static inline int rrc_stats_IndicationHeader_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_IndicationHeader_type_identifier, &rrc_stats_IndicationHeader_verify_table);
}

static inline int rrc_stats_IndicationHeader_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &rrc_stats_IndicationHeader_verify_table);
}

static inline int rrc_stats_IndicationHeader_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &rrc_stats_IndicationHeader_verify_table);
}

static int rrc_stats_MeasResult_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* rsrp */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* rsrq */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* sinr */)) return ret;
    return flatcc_verify_ok;
}

static inline int rrc_stats_MeasResult_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_MeasResult_identifier, &rrc_stats_MeasResult_verify_table);
}

static inline int rrc_stats_MeasResult_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_MeasResult_type_identifier, &rrc_stats_MeasResult_verify_table);
}

static inline int rrc_stats_MeasResult_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &rrc_stats_MeasResult_verify_table);
}

static inline int rrc_stats_MeasResult_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &rrc_stats_MeasResult_verify_table);
}

static int rrc_stats_NeighMeas_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* rat */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* phyCellId */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 2, 0, &rrc_common_PlmnInfo_verify_table) /* plmnInfo */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 3, 0, &rrc_stats_MeasResult_verify_table) /* measResult */)) return ret;
    return flatcc_verify_ok;
}

static inline int rrc_stats_NeighMeas_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_NeighMeas_identifier, &rrc_stats_NeighMeas_verify_table);
}

static inline int rrc_stats_NeighMeas_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_NeighMeas_type_identifier, &rrc_stats_NeighMeas_verify_table);
}

static inline int rrc_stats_NeighMeas_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &rrc_stats_NeighMeas_verify_table);
}

static inline int rrc_stats_NeighMeas_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &rrc_stats_NeighMeas_verify_table);
}

static int rrc_stats_MeasReport_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* measId */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 1, 0, &rrc_stats_MeasResult_verify_table) /* pCellResult */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 2, 0, &rrc_stats_NeighMeas_verify_table) /* neighMeas */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 3, 0, 1, 1, INT64_C(4294967295)) /* rrcContainer */)) return ret;
    return flatcc_verify_ok;
}

static inline int rrc_stats_MeasReport_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_MeasReport_identifier, &rrc_stats_MeasReport_verify_table);
}

static inline int rrc_stats_MeasReport_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_MeasReport_type_identifier, &rrc_stats_MeasReport_verify_table);
}

static inline int rrc_stats_MeasReport_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &rrc_stats_MeasReport_verify_table);
}

static inline int rrc_stats_MeasReport_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &rrc_stats_MeasReport_verify_table);
}

static int rrc_stats_IndicationMessage_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &rrc_stats_MeasReport_verify_table) /* measReport */)) return ret;
    return flatcc_verify_ok;
}

static inline int rrc_stats_IndicationMessage_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_IndicationMessage_identifier, &rrc_stats_IndicationMessage_verify_table);
}

static inline int rrc_stats_IndicationMessage_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_IndicationMessage_type_identifier, &rrc_stats_IndicationMessage_verify_table);
}

static inline int rrc_stats_IndicationMessage_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &rrc_stats_IndicationMessage_verify_table);
}

static inline int rrc_stats_IndicationMessage_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &rrc_stats_IndicationMessage_verify_table);
}

static int rrc_stats_RanFunctionDefinition_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &rrc_stats_ReportStyle_verify_table) /* supportedReportStyles */)) return ret;
    return flatcc_verify_ok;
}

static inline int rrc_stats_RanFunctionDefinition_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_RanFunctionDefinition_identifier, &rrc_stats_RanFunctionDefinition_verify_table);
}

static inline int rrc_stats_RanFunctionDefinition_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, rrc_stats_RanFunctionDefinition_type_identifier, &rrc_stats_RanFunctionDefinition_verify_table);
}

static inline int rrc_stats_RanFunctionDefinition_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &rrc_stats_RanFunctionDefinition_verify_table);
}

static inline int rrc_stats_RanFunctionDefinition_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &rrc_stats_RanFunctionDefinition_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* RRC_STATS_VERIFIER_H */
