#ifndef RRC_EVENT_BUILDER_H
#define RRC_EVENT_BUILDER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef RRC_EVENT_READER_H
#include "rrc_event_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#ifndef RRC_COMMON_BUILDER_H
#include "rrc_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif

#define __rrc_event_ReportOccasion_formal_args , rrc_event_ReportOccasion_enum_t v0
#define __rrc_event_ReportOccasion_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, rrc_event_ReportOccasion, rrc_event_ReportOccasion_enum_t)
#define __rrc_event_ReportStyleType_formal_args , rrc_event_ReportStyleType_enum_t v0
#define __rrc_event_ReportStyleType_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, rrc_event_ReportStyleType, rrc_event_ReportStyleType_enum_t)
#define __rrc_event_Event_formal_args , rrc_event_Event_enum_t v0
#define __rrc_event_Event_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, rrc_event_Event, rrc_event_Event_enum_t)

static const flatbuffers_voffset_t __rrc_event_EventTrigger_required[] = { 0 };
typedef flatbuffers_ref_t rrc_event_EventTrigger_ref_t;
static rrc_event_EventTrigger_ref_t rrc_event_EventTrigger_clone(flatbuffers_builder_t *B, rrc_event_EventTrigger_table_t t);
__flatbuffers_build_table(flatbuffers_, rrc_event_EventTrigger, 1)

static const flatbuffers_voffset_t __rrc_event_ReportStyle_required[] = { 0 };
typedef flatbuffers_ref_t rrc_event_ReportStyle_ref_t;
static rrc_event_ReportStyle_ref_t rrc_event_ReportStyle_clone(flatbuffers_builder_t *B, rrc_event_ReportStyle_table_t t);
__flatbuffers_build_table(flatbuffers_, rrc_event_ReportStyle, 1)

static const flatbuffers_voffset_t __rrc_event_ActionDefinition_required[] = { 0 };
typedef flatbuffers_ref_t rrc_event_ActionDefinition_ref_t;
static rrc_event_ActionDefinition_ref_t rrc_event_ActionDefinition_clone(flatbuffers_builder_t *B, rrc_event_ActionDefinition_table_t t);
__flatbuffers_build_table(flatbuffers_, rrc_event_ActionDefinition, 1)

static const flatbuffers_voffset_t __rrc_event_IndicationHeader_required[] = { 0 };
typedef flatbuffers_ref_t rrc_event_IndicationHeader_ref_t;
static rrc_event_IndicationHeader_ref_t rrc_event_IndicationHeader_clone(flatbuffers_builder_t *B, rrc_event_IndicationHeader_table_t t);
__flatbuffers_build_table(flatbuffers_, rrc_event_IndicationHeader, 2)

static const flatbuffers_voffset_t __rrc_event_LTECapability_required[] = { 0 };
typedef flatbuffers_ref_t rrc_event_LTECapability_ref_t;
static rrc_event_LTECapability_ref_t rrc_event_LTECapability_clone(flatbuffers_builder_t *B, rrc_event_LTECapability_table_t t);
__flatbuffers_build_table(flatbuffers_, rrc_event_LTECapability, 3)

static const flatbuffers_voffset_t __rrc_event_LteExt_required[] = { 0 };
typedef flatbuffers_ref_t rrc_event_LteExt_ref_t;
static rrc_event_LteExt_ref_t rrc_event_LteExt_clone(flatbuffers_builder_t *B, rrc_event_LteExt_table_t t);
__flatbuffers_build_table(flatbuffers_, rrc_event_LteExt, 1)

static const flatbuffers_voffset_t __rrc_event_NrExt_required[] = { 0 };
typedef flatbuffers_ref_t rrc_event_NrExt_ref_t;
static rrc_event_NrExt_ref_t rrc_event_NrExt_clone(flatbuffers_builder_t *B, rrc_event_NrExt_table_t t);
__flatbuffers_build_table(flatbuffers_, rrc_event_NrExt, 1)

static const flatbuffers_voffset_t __rrc_event_IndicationMessage_required[] = { 0 };
typedef flatbuffers_ref_t rrc_event_IndicationMessage_ref_t;
static rrc_event_IndicationMessage_ref_t rrc_event_IndicationMessage_clone(flatbuffers_builder_t *B, rrc_event_IndicationMessage_table_t t);
__flatbuffers_build_table(flatbuffers_, rrc_event_IndicationMessage, 6)

static const flatbuffers_voffset_t __rrc_event_RanFunctionDefinition_required[] = { 0 };
typedef flatbuffers_ref_t rrc_event_RanFunctionDefinition_ref_t;
static rrc_event_RanFunctionDefinition_ref_t rrc_event_RanFunctionDefinition_clone(flatbuffers_builder_t *B, rrc_event_RanFunctionDefinition_table_t t);
__flatbuffers_build_table(flatbuffers_, rrc_event_RanFunctionDefinition, 1)

#define __rrc_event_EventTrigger_formal_args , rrc_event_ReportOccasion_enum_t v0
#define __rrc_event_EventTrigger_call_args , v0
static inline rrc_event_EventTrigger_ref_t rrc_event_EventTrigger_create(flatbuffers_builder_t *B __rrc_event_EventTrigger_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, rrc_event_EventTrigger, rrc_event_EventTrigger_file_identifier, rrc_event_EventTrigger_type_identifier)

#define __rrc_event_ReportStyle_formal_args , rrc_event_ReportStyleType_enum_t v0
#define __rrc_event_ReportStyle_call_args , v0
static inline rrc_event_ReportStyle_ref_t rrc_event_ReportStyle_create(flatbuffers_builder_t *B __rrc_event_ReportStyle_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, rrc_event_ReportStyle, rrc_event_ReportStyle_file_identifier, rrc_event_ReportStyle_type_identifier)

#define __rrc_event_ActionDefinition_formal_args , rrc_event_ReportStyle_ref_t v0
#define __rrc_event_ActionDefinition_call_args , v0
static inline rrc_event_ActionDefinition_ref_t rrc_event_ActionDefinition_create(flatbuffers_builder_t *B __rrc_event_ActionDefinition_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, rrc_event_ActionDefinition, rrc_event_ActionDefinition_file_identifier, rrc_event_ActionDefinition_type_identifier)

#define __rrc_event_IndicationHeader_formal_args , uint16_t v0, rrc_event_Event_enum_t v1
#define __rrc_event_IndicationHeader_call_args , v0, v1
static inline rrc_event_IndicationHeader_ref_t rrc_event_IndicationHeader_create(flatbuffers_builder_t *B __rrc_event_IndicationHeader_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, rrc_event_IndicationHeader, rrc_event_IndicationHeader_file_identifier, rrc_event_IndicationHeader_type_identifier)

#define __rrc_event_LTECapability_formal_args , uint8_t v0, uint8_t v1, flatbuffers_bool_t v2
#define __rrc_event_LTECapability_call_args , v0, v1, v2
static inline rrc_event_LTECapability_ref_t rrc_event_LTECapability_create(flatbuffers_builder_t *B __rrc_event_LTECapability_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, rrc_event_LTECapability, rrc_event_LTECapability_file_identifier, rrc_event_LTECapability_type_identifier)

#define __rrc_event_LteExt_formal_args , rrc_event_LTECapability_ref_t v0
#define __rrc_event_LteExt_call_args , v0
static inline rrc_event_LteExt_ref_t rrc_event_LteExt_create(flatbuffers_builder_t *B __rrc_event_LteExt_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, rrc_event_LteExt, rrc_event_LteExt_file_identifier, rrc_event_LteExt_type_identifier)

#define __rrc_event_NrExt_formal_args , rrc_common_Snssai_vec_ref_t v0
#define __rrc_event_NrExt_call_args , v0
static inline rrc_event_NrExt_ref_t rrc_event_NrExt_create(flatbuffers_builder_t *B __rrc_event_NrExt_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, rrc_event_NrExt, rrc_event_NrExt_file_identifier, rrc_event_NrExt_type_identifier)

#define __rrc_event_IndicationMessage_formal_args ,\
  rrc_common_RAT_enum_t v0, uint8_t v1, flatbuffers_string_ref_t v2, flatbuffers_uint8_vec_ref_t v3, rrc_event_LteExt_ref_t v4, rrc_event_NrExt_ref_t v5
#define __rrc_event_IndicationMessage_call_args ,\
  v0, v1, v2, v3, v4, v5
static inline rrc_event_IndicationMessage_ref_t rrc_event_IndicationMessage_create(flatbuffers_builder_t *B __rrc_event_IndicationMessage_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, rrc_event_IndicationMessage, rrc_event_IndicationMessage_file_identifier, rrc_event_IndicationMessage_type_identifier)

#define __rrc_event_RanFunctionDefinition_formal_args , rrc_event_ReportStyle_vec_ref_t v0
#define __rrc_event_RanFunctionDefinition_call_args , v0
static inline rrc_event_RanFunctionDefinition_ref_t rrc_event_RanFunctionDefinition_create(flatbuffers_builder_t *B __rrc_event_RanFunctionDefinition_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, rrc_event_RanFunctionDefinition, rrc_event_RanFunctionDefinition_file_identifier, rrc_event_RanFunctionDefinition_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, rrc_event_EventTrigger_reportOccasion, rrc_event_ReportOccasion, rrc_event_ReportOccasion_enum_t, 1, 1, UINT8_C(0), rrc_event_EventTrigger)

static inline rrc_event_EventTrigger_ref_t rrc_event_EventTrigger_create(flatbuffers_builder_t *B __rrc_event_EventTrigger_formal_args)
{
    if (rrc_event_EventTrigger_start(B)
        || rrc_event_EventTrigger_reportOccasion_add(B, v0)) {
        return 0;
    }
    return rrc_event_EventTrigger_end(B);
}

static rrc_event_EventTrigger_ref_t rrc_event_EventTrigger_clone(flatbuffers_builder_t *B, rrc_event_EventTrigger_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (rrc_event_EventTrigger_start(B)
        || rrc_event_EventTrigger_reportOccasion_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, rrc_event_EventTrigger_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, rrc_event_ReportStyle_type, rrc_event_ReportStyleType, rrc_event_ReportStyleType_enum_t, 1, 1, UINT8_C(0), rrc_event_ReportStyle)

static inline rrc_event_ReportStyle_ref_t rrc_event_ReportStyle_create(flatbuffers_builder_t *B __rrc_event_ReportStyle_formal_args)
{
    if (rrc_event_ReportStyle_start(B)
        || rrc_event_ReportStyle_type_add(B, v0)) {
        return 0;
    }
    return rrc_event_ReportStyle_end(B);
}

static rrc_event_ReportStyle_ref_t rrc_event_ReportStyle_clone(flatbuffers_builder_t *B, rrc_event_ReportStyle_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (rrc_event_ReportStyle_start(B)
        || rrc_event_ReportStyle_type_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, rrc_event_ReportStyle_end(B));
}

__flatbuffers_build_table_field(0, flatbuffers_, rrc_event_ActionDefinition_reportStyle, rrc_event_ReportStyle, rrc_event_ActionDefinition)

static inline rrc_event_ActionDefinition_ref_t rrc_event_ActionDefinition_create(flatbuffers_builder_t *B __rrc_event_ActionDefinition_formal_args)
{
    if (rrc_event_ActionDefinition_start(B)
        || rrc_event_ActionDefinition_reportStyle_add(B, v0)) {
        return 0;
    }
    return rrc_event_ActionDefinition_end(B);
}

static rrc_event_ActionDefinition_ref_t rrc_event_ActionDefinition_clone(flatbuffers_builder_t *B, rrc_event_ActionDefinition_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (rrc_event_ActionDefinition_start(B)
        || rrc_event_ActionDefinition_reportStyle_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, rrc_event_ActionDefinition_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, rrc_event_IndicationHeader_rnti, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), rrc_event_IndicationHeader)
__flatbuffers_build_scalar_field(1, flatbuffers_, rrc_event_IndicationHeader_event, rrc_event_Event, rrc_event_Event_enum_t, 1, 1, UINT8_C(0), rrc_event_IndicationHeader)

static inline rrc_event_IndicationHeader_ref_t rrc_event_IndicationHeader_create(flatbuffers_builder_t *B __rrc_event_IndicationHeader_formal_args)
{
    if (rrc_event_IndicationHeader_start(B)
        || rrc_event_IndicationHeader_rnti_add(B, v0)
        || rrc_event_IndicationHeader_event_add(B, v1)) {
        return 0;
    }
    return rrc_event_IndicationHeader_end(B);
}

static rrc_event_IndicationHeader_ref_t rrc_event_IndicationHeader_clone(flatbuffers_builder_t *B, rrc_event_IndicationHeader_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (rrc_event_IndicationHeader_start(B)
        || rrc_event_IndicationHeader_rnti_pick(B, t)
        || rrc_event_IndicationHeader_event_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, rrc_event_IndicationHeader_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, rrc_event_LTECapability_dlUeCategory, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), rrc_event_LTECapability)
__flatbuffers_build_scalar_field(1, flatbuffers_, rrc_event_LTECapability_ulUeCategory, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), rrc_event_LTECapability)
__flatbuffers_build_scalar_field(2, flatbuffers_, rrc_event_LTECapability_enDC, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), rrc_event_LTECapability)

static inline rrc_event_LTECapability_ref_t rrc_event_LTECapability_create(flatbuffers_builder_t *B __rrc_event_LTECapability_formal_args)
{
    if (rrc_event_LTECapability_start(B)
        || rrc_event_LTECapability_dlUeCategory_add(B, v0)
        || rrc_event_LTECapability_ulUeCategory_add(B, v1)
        || rrc_event_LTECapability_enDC_add(B, v2)) {
        return 0;
    }
    return rrc_event_LTECapability_end(B);
}

static rrc_event_LTECapability_ref_t rrc_event_LTECapability_clone(flatbuffers_builder_t *B, rrc_event_LTECapability_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (rrc_event_LTECapability_start(B)
        || rrc_event_LTECapability_dlUeCategory_pick(B, t)
        || rrc_event_LTECapability_ulUeCategory_pick(B, t)
        || rrc_event_LTECapability_enDC_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, rrc_event_LTECapability_end(B));
}

__flatbuffers_build_table_field(0, flatbuffers_, rrc_event_LteExt_lteCapability, rrc_event_LTECapability, rrc_event_LteExt)

static inline rrc_event_LteExt_ref_t rrc_event_LteExt_create(flatbuffers_builder_t *B __rrc_event_LteExt_formal_args)
{
    if (rrc_event_LteExt_start(B)
        || rrc_event_LteExt_lteCapability_add(B, v0)) {
        return 0;
    }
    return rrc_event_LteExt_end(B);
}

static rrc_event_LteExt_ref_t rrc_event_LteExt_clone(flatbuffers_builder_t *B, rrc_event_LteExt_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (rrc_event_LteExt_start(B)
        || rrc_event_LteExt_lteCapability_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, rrc_event_LteExt_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, rrc_event_NrExt_sNssaiList, rrc_common_Snssai, rrc_event_NrExt)

static inline rrc_event_NrExt_ref_t rrc_event_NrExt_create(flatbuffers_builder_t *B __rrc_event_NrExt_formal_args)
{
    if (rrc_event_NrExt_start(B)
        || rrc_event_NrExt_sNssaiList_add(B, v0)) {
        return 0;
    }
    return rrc_event_NrExt_end(B);
}

static rrc_event_NrExt_ref_t rrc_event_NrExt_clone(flatbuffers_builder_t *B, rrc_event_NrExt_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (rrc_event_NrExt_start(B)
        || rrc_event_NrExt_sNssaiList_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, rrc_event_NrExt_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, rrc_event_IndicationMessage_rat, rrc_common_RAT, rrc_common_RAT_enum_t, 1, 1, UINT8_C(0), rrc_event_IndicationMessage)
__flatbuffers_build_scalar_field(1, flatbuffers_, rrc_event_IndicationMessage_selectedPlmnId, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), rrc_event_IndicationMessage)
__flatbuffers_build_string_field(2, flatbuffers_, rrc_event_IndicationMessage_imsi, rrc_event_IndicationMessage)
__flatbuffers_build_vector_field(3, flatbuffers_, rrc_event_IndicationMessage_ueCapabilityRrcContainer, flatbuffers_uint8, uint8_t, rrc_event_IndicationMessage)
__flatbuffers_build_table_field(4, flatbuffers_, rrc_event_IndicationMessage_lteExt, rrc_event_LteExt, rrc_event_IndicationMessage)
__flatbuffers_build_table_field(5, flatbuffers_, rrc_event_IndicationMessage_nrExt, rrc_event_NrExt, rrc_event_IndicationMessage)

static inline rrc_event_IndicationMessage_ref_t rrc_event_IndicationMessage_create(flatbuffers_builder_t *B __rrc_event_IndicationMessage_formal_args)
{
    if (rrc_event_IndicationMessage_start(B)
        || rrc_event_IndicationMessage_imsi_add(B, v2)
        || rrc_event_IndicationMessage_ueCapabilityRrcContainer_add(B, v3)
        || rrc_event_IndicationMessage_lteExt_add(B, v4)
        || rrc_event_IndicationMessage_nrExt_add(B, v5)
        || rrc_event_IndicationMessage_rat_add(B, v0)
        || rrc_event_IndicationMessage_selectedPlmnId_add(B, v1)) {
        return 0;
    }
    return rrc_event_IndicationMessage_end(B);
}

static rrc_event_IndicationMessage_ref_t rrc_event_IndicationMessage_clone(flatbuffers_builder_t *B, rrc_event_IndicationMessage_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (rrc_event_IndicationMessage_start(B)
        || rrc_event_IndicationMessage_imsi_pick(B, t)
        || rrc_event_IndicationMessage_ueCapabilityRrcContainer_pick(B, t)
        || rrc_event_IndicationMessage_lteExt_pick(B, t)
        || rrc_event_IndicationMessage_nrExt_pick(B, t)
        || rrc_event_IndicationMessage_rat_pick(B, t)
        || rrc_event_IndicationMessage_selectedPlmnId_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, rrc_event_IndicationMessage_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, rrc_event_RanFunctionDefinition_supportedReportStyles, rrc_event_ReportStyle, rrc_event_RanFunctionDefinition)

static inline rrc_event_RanFunctionDefinition_ref_t rrc_event_RanFunctionDefinition_create(flatbuffers_builder_t *B __rrc_event_RanFunctionDefinition_formal_args)
{
    if (rrc_event_RanFunctionDefinition_start(B)
        || rrc_event_RanFunctionDefinition_supportedReportStyles_add(B, v0)) {
        return 0;
    }
    return rrc_event_RanFunctionDefinition_end(B);
}

static rrc_event_RanFunctionDefinition_ref_t rrc_event_RanFunctionDefinition_clone(flatbuffers_builder_t *B, rrc_event_RanFunctionDefinition_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (rrc_event_RanFunctionDefinition_start(B)
        || rrc_event_RanFunctionDefinition_supportedReportStyles_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, rrc_event_RanFunctionDefinition_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* RRC_EVENT_BUILDER_H */
