#ifndef RSLICING_READER_H
#define RSLICING_READER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct mac_rslicing_StaticSlice_table *mac_rslicing_StaticSlice_table_t;
typedef struct mac_rslicing_StaticSlice_table *mac_rslicing_StaticSlice_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_StaticSlice_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_StaticSlice_mutable_vec_t;
typedef const struct mac_rslicing_NvsRate_table *mac_rslicing_NvsRate_table_t;
typedef struct mac_rslicing_NvsRate_table *mac_rslicing_NvsRate_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_NvsRate_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_NvsRate_mutable_vec_t;
typedef const struct mac_rslicing_NvsCapacity_table *mac_rslicing_NvsCapacity_table_t;
typedef struct mac_rslicing_NvsCapacity_table *mac_rslicing_NvsCapacity_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_NvsCapacity_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_NvsCapacity_mutable_vec_t;
typedef const struct mac_rslicing_NvsSlice_table *mac_rslicing_NvsSlice_table_t;
typedef struct mac_rslicing_NvsSlice_table *mac_rslicing_NvsSlice_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_NvsSlice_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_NvsSlice_mutable_vec_t;
typedef const struct mac_rslicing_Scn19OnDemand_table *mac_rslicing_Scn19OnDemand_table_t;
typedef struct mac_rslicing_Scn19OnDemand_table *mac_rslicing_Scn19OnDemand_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_Scn19OnDemand_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_Scn19OnDemand_mutable_vec_t;
typedef const struct mac_rslicing_Scn19Slice_table *mac_rslicing_Scn19Slice_table_t;
typedef struct mac_rslicing_Scn19Slice_table *mac_rslicing_Scn19Slice_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_Scn19Slice_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_Scn19Slice_mutable_vec_t;
typedef const struct mac_rslicing_EdfSlice_table *mac_rslicing_EdfSlice_table_t;
typedef struct mac_rslicing_EdfSlice_table *mac_rslicing_EdfSlice_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_EdfSlice_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_EdfSlice_mutable_vec_t;
typedef const struct mac_rslicing_Slice_table *mac_rslicing_Slice_table_t;
typedef struct mac_rslicing_Slice_table *mac_rslicing_Slice_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_Slice_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_Slice_mutable_vec_t;
typedef const struct mac_rslicing_UlDlSliceConfig_table *mac_rslicing_UlDlSliceConfig_table_t;
typedef struct mac_rslicing_UlDlSliceConfig_table *mac_rslicing_UlDlSliceConfig_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_UlDlSliceConfig_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_UlDlSliceConfig_mutable_vec_t;
typedef const struct mac_rslicing_SliceConfig_table *mac_rslicing_SliceConfig_table_t;
typedef struct mac_rslicing_SliceConfig_table *mac_rslicing_SliceConfig_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_SliceConfig_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_SliceConfig_mutable_vec_t;
typedef const struct mac_rslicing_UeSliceAssoc_table *mac_rslicing_UeSliceAssoc_table_t;
typedef struct mac_rslicing_UeSliceAssoc_table *mac_rslicing_UeSliceAssoc_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_UeSliceAssoc_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_UeSliceAssoc_mutable_vec_t;
typedef const struct mac_rslicing_UeSliceConfig_table *mac_rslicing_UeSliceConfig_table_t;
typedef struct mac_rslicing_UeSliceConfig_table *mac_rslicing_UeSliceConfig_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_UeSliceConfig_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_UeSliceConfig_mutable_vec_t;
typedef const struct mac_rslicing_DelSliceConfig_table *mac_rslicing_DelSliceConfig_table_t;
typedef struct mac_rslicing_DelSliceConfig_table *mac_rslicing_DelSliceConfig_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_DelSliceConfig_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_DelSliceConfig_mutable_vec_t;
typedef const struct mac_rslicing_EventTrigger_table *mac_rslicing_EventTrigger_table_t;
typedef struct mac_rslicing_EventTrigger_table *mac_rslicing_EventTrigger_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_EventTrigger_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_EventTrigger_mutable_vec_t;
typedef const struct mac_rslicing_IndicationHeader_table *mac_rslicing_IndicationHeader_table_t;
typedef struct mac_rslicing_IndicationHeader_table *mac_rslicing_IndicationHeader_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_IndicationHeader_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_IndicationHeader_mutable_vec_t;
typedef const struct mac_rslicing_IndicationMessage_table *mac_rslicing_IndicationMessage_table_t;
typedef struct mac_rslicing_IndicationMessage_table *mac_rslicing_IndicationMessage_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_IndicationMessage_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_IndicationMessage_mutable_vec_t;
typedef const struct mac_rslicing_ControlHeader_table *mac_rslicing_ControlHeader_table_t;
typedef struct mac_rslicing_ControlHeader_table *mac_rslicing_ControlHeader_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_ControlHeader_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_ControlHeader_mutable_vec_t;
typedef const struct mac_rslicing_AddModSliceCommand_table *mac_rslicing_AddModSliceCommand_table_t;
typedef struct mac_rslicing_AddModSliceCommand_table *mac_rslicing_AddModSliceCommand_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_AddModSliceCommand_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_AddModSliceCommand_mutable_vec_t;
typedef const struct mac_rslicing_DelSliceCommand_table *mac_rslicing_DelSliceCommand_table_t;
typedef struct mac_rslicing_DelSliceCommand_table *mac_rslicing_DelSliceCommand_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_DelSliceCommand_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_DelSliceCommand_mutable_vec_t;
typedef const struct mac_rslicing_UeSliceAssocCommand_table *mac_rslicing_UeSliceAssocCommand_table_t;
typedef struct mac_rslicing_UeSliceAssocCommand_table *mac_rslicing_UeSliceAssocCommand_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_UeSliceAssocCommand_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_UeSliceAssocCommand_mutable_vec_t;
typedef const struct mac_rslicing_ControlMessage_table *mac_rslicing_ControlMessage_table_t;
typedef struct mac_rslicing_ControlMessage_table *mac_rslicing_ControlMessage_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_ControlMessage_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_ControlMessage_mutable_vec_t;
typedef const struct mac_rslicing_ControlOutcome_table *mac_rslicing_ControlOutcome_table_t;
typedef struct mac_rslicing_ControlOutcome_table *mac_rslicing_ControlOutcome_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_ControlOutcome_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_ControlOutcome_mutable_vec_t;
typedef const struct mac_rslicing_CallProcessId_table *mac_rslicing_CallProcessId_table_t;
typedef struct mac_rslicing_CallProcessId_table *mac_rslicing_CallProcessId_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_CallProcessId_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_CallProcessId_mutable_vec_t;
typedef const struct mac_rslicing_SupportedAlgorithm_table *mac_rslicing_SupportedAlgorithm_table_t;
typedef struct mac_rslicing_SupportedAlgorithm_table *mac_rslicing_SupportedAlgorithm_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_SupportedAlgorithm_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_SupportedAlgorithm_mutable_vec_t;
typedef const struct mac_rslicing_RanFunctionDefinition_table *mac_rslicing_RanFunctionDefinition_table_t;
typedef struct mac_rslicing_RanFunctionDefinition_table *mac_rslicing_RanFunctionDefinition_mutable_table_t;
typedef const flatbuffers_uoffset_t *mac_rslicing_RanFunctionDefinition_vec_t;
typedef flatbuffers_uoffset_t *mac_rslicing_RanFunctionDefinition_mutable_vec_t;
#ifndef mac_rslicing_StaticSlice_file_identifier
#define mac_rslicing_StaticSlice_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_StaticSlice_file_identifier */
#ifndef mac_rslicing_StaticSlice_identifier
#define mac_rslicing_StaticSlice_identifier flatbuffers_identifier
#endif
#define mac_rslicing_StaticSlice_type_hash ((flatbuffers_thash_t)0xcafd5647)
#define mac_rslicing_StaticSlice_type_identifier "\x47\x56\xfd\xca"
#ifndef mac_rslicing_NvsRate_file_identifier
#define mac_rslicing_NvsRate_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_NvsRate_file_identifier */
#ifndef mac_rslicing_NvsRate_identifier
#define mac_rslicing_NvsRate_identifier flatbuffers_identifier
#endif
#define mac_rslicing_NvsRate_type_hash ((flatbuffers_thash_t)0x8cb26014)
#define mac_rslicing_NvsRate_type_identifier "\x14\x60\xb2\x8c"
#ifndef mac_rslicing_NvsCapacity_file_identifier
#define mac_rslicing_NvsCapacity_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_NvsCapacity_file_identifier */
#ifndef mac_rslicing_NvsCapacity_identifier
#define mac_rslicing_NvsCapacity_identifier flatbuffers_identifier
#endif
#define mac_rslicing_NvsCapacity_type_hash ((flatbuffers_thash_t)0x97ed847a)
#define mac_rslicing_NvsCapacity_type_identifier "\x7a\x84\xed\x97"
#ifndef mac_rslicing_NvsSlice_file_identifier
#define mac_rslicing_NvsSlice_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_NvsSlice_file_identifier */
#ifndef mac_rslicing_NvsSlice_identifier
#define mac_rslicing_NvsSlice_identifier flatbuffers_identifier
#endif
#define mac_rslicing_NvsSlice_type_hash ((flatbuffers_thash_t)0x5cbe3db4)
#define mac_rslicing_NvsSlice_type_identifier "\xb4\x3d\xbe\x5c"
#ifndef mac_rslicing_Scn19OnDemand_file_identifier
#define mac_rslicing_Scn19OnDemand_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_Scn19OnDemand_file_identifier */
#ifndef mac_rslicing_Scn19OnDemand_identifier
#define mac_rslicing_Scn19OnDemand_identifier flatbuffers_identifier
#endif
#define mac_rslicing_Scn19OnDemand_type_hash ((flatbuffers_thash_t)0xfcc1cdb)
#define mac_rslicing_Scn19OnDemand_type_identifier "\xdb\x1c\xcc\x0f"
#ifndef mac_rslicing_Scn19Slice_file_identifier
#define mac_rslicing_Scn19Slice_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_Scn19Slice_file_identifier */
#ifndef mac_rslicing_Scn19Slice_identifier
#define mac_rslicing_Scn19Slice_identifier flatbuffers_identifier
#endif
#define mac_rslicing_Scn19Slice_type_hash ((flatbuffers_thash_t)0x9e0a58f9)
#define mac_rslicing_Scn19Slice_type_identifier "\xf9\x58\x0a\x9e"
#ifndef mac_rslicing_EdfSlice_file_identifier
#define mac_rslicing_EdfSlice_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_EdfSlice_file_identifier */
#ifndef mac_rslicing_EdfSlice_identifier
#define mac_rslicing_EdfSlice_identifier flatbuffers_identifier
#endif
#define mac_rslicing_EdfSlice_type_hash ((flatbuffers_thash_t)0xf486a470)
#define mac_rslicing_EdfSlice_type_identifier "\x70\xa4\x86\xf4"
#ifndef mac_rslicing_Slice_file_identifier
#define mac_rslicing_Slice_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_Slice_file_identifier */
#ifndef mac_rslicing_Slice_identifier
#define mac_rslicing_Slice_identifier flatbuffers_identifier
#endif
#define mac_rslicing_Slice_type_hash ((flatbuffers_thash_t)0xbdeeaca5)
#define mac_rslicing_Slice_type_identifier "\xa5\xac\xee\xbd"
#ifndef mac_rslicing_UlDlSliceConfig_file_identifier
#define mac_rslicing_UlDlSliceConfig_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_UlDlSliceConfig_file_identifier */
#ifndef mac_rslicing_UlDlSliceConfig_identifier
#define mac_rslicing_UlDlSliceConfig_identifier flatbuffers_identifier
#endif
#define mac_rslicing_UlDlSliceConfig_type_hash ((flatbuffers_thash_t)0xc3947c4c)
#define mac_rslicing_UlDlSliceConfig_type_identifier "\x4c\x7c\x94\xc3"
#ifndef mac_rslicing_SliceConfig_file_identifier
#define mac_rslicing_SliceConfig_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_SliceConfig_file_identifier */
#ifndef mac_rslicing_SliceConfig_identifier
#define mac_rslicing_SliceConfig_identifier flatbuffers_identifier
#endif
#define mac_rslicing_SliceConfig_type_hash ((flatbuffers_thash_t)0x3b616587)
#define mac_rslicing_SliceConfig_type_identifier "\x87\x65\x61\x3b"
#ifndef mac_rslicing_UeSliceAssoc_file_identifier
#define mac_rslicing_UeSliceAssoc_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_UeSliceAssoc_file_identifier */
#ifndef mac_rslicing_UeSliceAssoc_identifier
#define mac_rslicing_UeSliceAssoc_identifier flatbuffers_identifier
#endif
#define mac_rslicing_UeSliceAssoc_type_hash ((flatbuffers_thash_t)0xd6fce2e6)
#define mac_rslicing_UeSliceAssoc_type_identifier "\xe6\xe2\xfc\xd6"
#ifndef mac_rslicing_UeSliceConfig_file_identifier
#define mac_rslicing_UeSliceConfig_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_UeSliceConfig_file_identifier */
#ifndef mac_rslicing_UeSliceConfig_identifier
#define mac_rslicing_UeSliceConfig_identifier flatbuffers_identifier
#endif
#define mac_rslicing_UeSliceConfig_type_hash ((flatbuffers_thash_t)0x4dbe5c81)
#define mac_rslicing_UeSliceConfig_type_identifier "\x81\x5c\xbe\x4d"
#ifndef mac_rslicing_DelSliceConfig_file_identifier
#define mac_rslicing_DelSliceConfig_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_DelSliceConfig_file_identifier */
#ifndef mac_rslicing_DelSliceConfig_identifier
#define mac_rslicing_DelSliceConfig_identifier flatbuffers_identifier
#endif
#define mac_rslicing_DelSliceConfig_type_hash ((flatbuffers_thash_t)0x7cb61e72)
#define mac_rslicing_DelSliceConfig_type_identifier "\x72\x1e\xb6\x7c"
#ifndef mac_rslicing_EventTrigger_file_identifier
#define mac_rslicing_EventTrigger_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_EventTrigger_file_identifier */
#ifndef mac_rslicing_EventTrigger_identifier
#define mac_rslicing_EventTrigger_identifier flatbuffers_identifier
#endif
#define mac_rslicing_EventTrigger_type_hash ((flatbuffers_thash_t)0xfba7af95)
#define mac_rslicing_EventTrigger_type_identifier "\x95\xaf\xa7\xfb"
#ifndef mac_rslicing_IndicationHeader_file_identifier
#define mac_rslicing_IndicationHeader_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_IndicationHeader_file_identifier */
#ifndef mac_rslicing_IndicationHeader_identifier
#define mac_rslicing_IndicationHeader_identifier flatbuffers_identifier
#endif
#define mac_rslicing_IndicationHeader_type_hash ((flatbuffers_thash_t)0x9f814dce)
#define mac_rslicing_IndicationHeader_type_identifier "\xce\x4d\x81\x9f"
#ifndef mac_rslicing_IndicationMessage_file_identifier
#define mac_rslicing_IndicationMessage_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_IndicationMessage_file_identifier */
#ifndef mac_rslicing_IndicationMessage_identifier
#define mac_rslicing_IndicationMessage_identifier flatbuffers_identifier
#endif
#define mac_rslicing_IndicationMessage_type_hash ((flatbuffers_thash_t)0x6c9ef066)
#define mac_rslicing_IndicationMessage_type_identifier "\x66\xf0\x9e\x6c"
#ifndef mac_rslicing_ControlHeader_file_identifier
#define mac_rslicing_ControlHeader_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_ControlHeader_file_identifier */
#ifndef mac_rslicing_ControlHeader_identifier
#define mac_rslicing_ControlHeader_identifier flatbuffers_identifier
#endif
#define mac_rslicing_ControlHeader_type_hash ((flatbuffers_thash_t)0xfa6aea43)
#define mac_rslicing_ControlHeader_type_identifier "\x43\xea\x6a\xfa"
#ifndef mac_rslicing_AddModSliceCommand_file_identifier
#define mac_rslicing_AddModSliceCommand_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_AddModSliceCommand_file_identifier */
#ifndef mac_rslicing_AddModSliceCommand_identifier
#define mac_rslicing_AddModSliceCommand_identifier flatbuffers_identifier
#endif
#define mac_rslicing_AddModSliceCommand_type_hash ((flatbuffers_thash_t)0x27f38ce7)
#define mac_rslicing_AddModSliceCommand_type_identifier "\xe7\x8c\xf3\x27"
#ifndef mac_rslicing_DelSliceCommand_file_identifier
#define mac_rslicing_DelSliceCommand_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_DelSliceCommand_file_identifier */
#ifndef mac_rslicing_DelSliceCommand_identifier
#define mac_rslicing_DelSliceCommand_identifier flatbuffers_identifier
#endif
#define mac_rslicing_DelSliceCommand_type_hash ((flatbuffers_thash_t)0x9e04121d)
#define mac_rslicing_DelSliceCommand_type_identifier "\x1d\x12\x04\x9e"
#ifndef mac_rslicing_UeSliceAssocCommand_file_identifier
#define mac_rslicing_UeSliceAssocCommand_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_UeSliceAssocCommand_file_identifier */
#ifndef mac_rslicing_UeSliceAssocCommand_identifier
#define mac_rslicing_UeSliceAssocCommand_identifier flatbuffers_identifier
#endif
#define mac_rslicing_UeSliceAssocCommand_type_hash ((flatbuffers_thash_t)0xfb055c7)
#define mac_rslicing_UeSliceAssocCommand_type_identifier "\xc7\x55\xb0\x0f"
#ifndef mac_rslicing_ControlMessage_file_identifier
#define mac_rslicing_ControlMessage_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_ControlMessage_file_identifier */
#ifndef mac_rslicing_ControlMessage_identifier
#define mac_rslicing_ControlMessage_identifier flatbuffers_identifier
#endif
#define mac_rslicing_ControlMessage_type_hash ((flatbuffers_thash_t)0xeb0293a1)
#define mac_rslicing_ControlMessage_type_identifier "\xa1\x93\x02\xeb"
#ifndef mac_rslicing_ControlOutcome_file_identifier
#define mac_rslicing_ControlOutcome_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_ControlOutcome_file_identifier */
#ifndef mac_rslicing_ControlOutcome_identifier
#define mac_rslicing_ControlOutcome_identifier flatbuffers_identifier
#endif
#define mac_rslicing_ControlOutcome_type_hash ((flatbuffers_thash_t)0xd8e3744e)
#define mac_rslicing_ControlOutcome_type_identifier "\x4e\x74\xe3\xd8"
#ifndef mac_rslicing_CallProcessId_file_identifier
#define mac_rslicing_CallProcessId_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_CallProcessId_file_identifier */
#ifndef mac_rslicing_CallProcessId_identifier
#define mac_rslicing_CallProcessId_identifier flatbuffers_identifier
#endif
#define mac_rslicing_CallProcessId_type_hash ((flatbuffers_thash_t)0xbf1a79e7)
#define mac_rslicing_CallProcessId_type_identifier "\xe7\x79\x1a\xbf"
#ifndef mac_rslicing_SupportedAlgorithm_file_identifier
#define mac_rslicing_SupportedAlgorithm_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_SupportedAlgorithm_file_identifier */
#ifndef mac_rslicing_SupportedAlgorithm_identifier
#define mac_rslicing_SupportedAlgorithm_identifier flatbuffers_identifier
#endif
#define mac_rslicing_SupportedAlgorithm_type_hash ((flatbuffers_thash_t)0xea2fefba)
#define mac_rslicing_SupportedAlgorithm_type_identifier "\xba\xef\x2f\xea"
#ifndef mac_rslicing_RanFunctionDefinition_file_identifier
#define mac_rslicing_RanFunctionDefinition_file_identifier flatbuffers_identifier
#endif
/* deprecated, use mac_rslicing_RanFunctionDefinition_file_identifier */
#ifndef mac_rslicing_RanFunctionDefinition_identifier
#define mac_rslicing_RanFunctionDefinition_identifier flatbuffers_identifier
#endif
#define mac_rslicing_RanFunctionDefinition_type_hash ((flatbuffers_thash_t)0xba06fbf)
#define mac_rslicing_RanFunctionDefinition_type_identifier "\xbf\x6f\xa0\x0b"

typedef uint8_t mac_rslicing_SliceAlgorithm_enum_t;
__flatbuffers_define_integer_type(mac_rslicing_SliceAlgorithm, mac_rslicing_SliceAlgorithm_enum_t, 8)
#define mac_rslicing_SliceAlgorithm_None ((mac_rslicing_SliceAlgorithm_enum_t)UINT8_C(0))
#define mac_rslicing_SliceAlgorithm_Static ((mac_rslicing_SliceAlgorithm_enum_t)UINT8_C(1))
#define mac_rslicing_SliceAlgorithm_NVS ((mac_rslicing_SliceAlgorithm_enum_t)UINT8_C(2))
#define mac_rslicing_SliceAlgorithm_SCN19 ((mac_rslicing_SliceAlgorithm_enum_t)UINT8_C(3))
#define mac_rslicing_SliceAlgorithm_EDF ((mac_rslicing_SliceAlgorithm_enum_t)UINT8_C(4))

static inline const char *mac_rslicing_SliceAlgorithm_name(mac_rslicing_SliceAlgorithm_enum_t value)
{
    switch (value) {
    case mac_rslicing_SliceAlgorithm_None: return "None";
    case mac_rslicing_SliceAlgorithm_Static: return "Static";
    case mac_rslicing_SliceAlgorithm_NVS: return "NVS";
    case mac_rslicing_SliceAlgorithm_SCN19: return "SCN19";
    case mac_rslicing_SliceAlgorithm_EDF: return "EDF";
    default: return "";
    }
}

static inline int mac_rslicing_SliceAlgorithm_is_known_value(mac_rslicing_SliceAlgorithm_enum_t value)
{
    switch (value) {
    case mac_rslicing_SliceAlgorithm_None: return 1;
    case mac_rslicing_SliceAlgorithm_Static: return 1;
    case mac_rslicing_SliceAlgorithm_NVS: return 1;
    case mac_rslicing_SliceAlgorithm_SCN19: return 1;
    case mac_rslicing_SliceAlgorithm_EDF: return 1;
    default: return 0;
    }
}

typedef uint8_t mac_rslicing_ReportOccasion_enum_t;
__flatbuffers_define_integer_type(mac_rslicing_ReportOccasion, mac_rslicing_ReportOccasion_enum_t, 8)
#define mac_rslicing_ReportOccasion_onChange ((mac_rslicing_ReportOccasion_enum_t)UINT8_C(0))

static inline const char *mac_rslicing_ReportOccasion_name(mac_rslicing_ReportOccasion_enum_t value)
{
    switch (value) {
    case mac_rslicing_ReportOccasion_onChange: return "onChange";
    default: return "";
    }
}

static inline int mac_rslicing_ReportOccasion_is_known_value(mac_rslicing_ReportOccasion_enum_t value)
{
    switch (value) {
    case mac_rslicing_ReportOccasion_onChange: return 1;
    default: return 0;
    }
}



struct mac_rslicing_StaticSlice_table { uint8_t unused__; };

static inline size_t mac_rslicing_StaticSlice_vec_len(mac_rslicing_StaticSlice_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_StaticSlice_table_t mac_rslicing_StaticSlice_vec_at(mac_rslicing_StaticSlice_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_StaticSlice_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_StaticSlice)

__flatbuffers_define_scalar_field(0, mac_rslicing_StaticSlice, posLow, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, mac_rslicing_StaticSlice, posHigh, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct mac_rslicing_NvsRate_table { uint8_t unused__; };

static inline size_t mac_rslicing_NvsRate_vec_len(mac_rslicing_NvsRate_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_NvsRate_table_t mac_rslicing_NvsRate_vec_at(mac_rslicing_NvsRate_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_NvsRate_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_NvsRate)

__flatbuffers_define_scalar_field(0, mac_rslicing_NvsRate, mbpsRequired, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(1, mac_rslicing_NvsRate, mbpsReference, flatbuffers_float, float, 0.00000000f)

struct mac_rslicing_NvsCapacity_table { uint8_t unused__; };

static inline size_t mac_rslicing_NvsCapacity_vec_len(mac_rslicing_NvsCapacity_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_NvsCapacity_table_t mac_rslicing_NvsCapacity_vec_at(mac_rslicing_NvsCapacity_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_NvsCapacity_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_NvsCapacity)

__flatbuffers_define_scalar_field(0, mac_rslicing_NvsCapacity, pctReserved, flatbuffers_float, float, 0.00000000f)
typedef uint8_t mac_rslicing_NvsSliceConfig_union_type_t;
__flatbuffers_define_integer_type(mac_rslicing_NvsSliceConfig, mac_rslicing_NvsSliceConfig_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, mac_rslicing_NvsSliceConfig)
#define mac_rslicing_NvsSliceConfig_NONE ((mac_rslicing_NvsSliceConfig_union_type_t)UINT8_C(0))
#define mac_rslicing_NvsSliceConfig_rate ((mac_rslicing_NvsSliceConfig_union_type_t)UINT8_C(1))
#define mac_rslicing_NvsSliceConfig_capacity ((mac_rslicing_NvsSliceConfig_union_type_t)UINT8_C(2))

static inline const char *mac_rslicing_NvsSliceConfig_type_name(mac_rslicing_NvsSliceConfig_union_type_t type)
{
    switch (type) {
    case mac_rslicing_NvsSliceConfig_NONE: return "NONE";
    case mac_rslicing_NvsSliceConfig_rate: return "rate";
    case mac_rslicing_NvsSliceConfig_capacity: return "capacity";
    default: return "";
    }
}

static inline int mac_rslicing_NvsSliceConfig_is_known_type(mac_rslicing_NvsSliceConfig_union_type_t type)
{
    switch (type) {
    case mac_rslicing_NvsSliceConfig_NONE: return 1;
    case mac_rslicing_NvsSliceConfig_rate: return 1;
    case mac_rslicing_NvsSliceConfig_capacity: return 1;
    default: return 0;
    }
}


struct mac_rslicing_NvsSlice_table { uint8_t unused__; };

static inline size_t mac_rslicing_NvsSlice_vec_len(mac_rslicing_NvsSlice_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_NvsSlice_table_t mac_rslicing_NvsSlice_vec_at(mac_rslicing_NvsSlice_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_NvsSlice_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_NvsSlice)

__flatbuffers_define_union_field(flatbuffers_, 1, mac_rslicing_NvsSlice, config, mac_rslicing_NvsSliceConfig, 0)

struct mac_rslicing_Scn19OnDemand_table { uint8_t unused__; };

static inline size_t mac_rslicing_Scn19OnDemand_vec_len(mac_rslicing_Scn19OnDemand_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_Scn19OnDemand_table_t mac_rslicing_Scn19OnDemand_vec_at(mac_rslicing_Scn19OnDemand_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_Scn19OnDemand_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_Scn19OnDemand)

__flatbuffers_define_scalar_field(0, mac_rslicing_Scn19OnDemand, pctReserved, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(1, mac_rslicing_Scn19OnDemand, tau, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, mac_rslicing_Scn19OnDemand, logDelta, flatbuffers_float, float, 0.00000000f)
typedef uint8_t mac_rslicing_Scn19SliceConfig_union_type_t;
__flatbuffers_define_integer_type(mac_rslicing_Scn19SliceConfig, mac_rslicing_Scn19SliceConfig_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, mac_rslicing_Scn19SliceConfig)
#define mac_rslicing_Scn19SliceConfig_NONE ((mac_rslicing_Scn19SliceConfig_union_type_t)UINT8_C(0))
#define mac_rslicing_Scn19SliceConfig_dynamic ((mac_rslicing_Scn19SliceConfig_union_type_t)UINT8_C(1))
#define mac_rslicing_Scn19SliceConfig_fixed ((mac_rslicing_Scn19SliceConfig_union_type_t)UINT8_C(2))
#define mac_rslicing_Scn19SliceConfig_ondemand ((mac_rslicing_Scn19SliceConfig_union_type_t)UINT8_C(3))

static inline const char *mac_rslicing_Scn19SliceConfig_type_name(mac_rslicing_Scn19SliceConfig_union_type_t type)
{
    switch (type) {
    case mac_rslicing_Scn19SliceConfig_NONE: return "NONE";
    case mac_rslicing_Scn19SliceConfig_dynamic: return "dynamic";
    case mac_rslicing_Scn19SliceConfig_fixed: return "fixed";
    case mac_rslicing_Scn19SliceConfig_ondemand: return "ondemand";
    default: return "";
    }
}

static inline int mac_rslicing_Scn19SliceConfig_is_known_type(mac_rslicing_Scn19SliceConfig_union_type_t type)
{
    switch (type) {
    case mac_rslicing_Scn19SliceConfig_NONE: return 1;
    case mac_rslicing_Scn19SliceConfig_dynamic: return 1;
    case mac_rslicing_Scn19SliceConfig_fixed: return 1;
    case mac_rslicing_Scn19SliceConfig_ondemand: return 1;
    default: return 0;
    }
}


struct mac_rslicing_Scn19Slice_table { uint8_t unused__; };

static inline size_t mac_rslicing_Scn19Slice_vec_len(mac_rslicing_Scn19Slice_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_Scn19Slice_table_t mac_rslicing_Scn19Slice_vec_at(mac_rslicing_Scn19Slice_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_Scn19Slice_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_Scn19Slice)

__flatbuffers_define_union_field(flatbuffers_, 1, mac_rslicing_Scn19Slice, config, mac_rslicing_Scn19SliceConfig, 0)

struct mac_rslicing_EdfSlice_table { uint8_t unused__; };

static inline size_t mac_rslicing_EdfSlice_vec_len(mac_rslicing_EdfSlice_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_EdfSlice_table_t mac_rslicing_EdfSlice_vec_at(mac_rslicing_EdfSlice_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_EdfSlice_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_EdfSlice)

__flatbuffers_define_scalar_field(0, mac_rslicing_EdfSlice, deadline, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, mac_rslicing_EdfSlice, guaranteedPrbs, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, mac_rslicing_EdfSlice, maxReplenish, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_vector_field(3, mac_rslicing_EdfSlice, override, flatbuffers_uint32_vec_t, 0)
typedef uint8_t mac_rslicing_SliceParams_union_type_t;
__flatbuffers_define_integer_type(mac_rslicing_SliceParams, mac_rslicing_SliceParams_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, mac_rslicing_SliceParams)
#define mac_rslicing_SliceParams_NONE ((mac_rslicing_SliceParams_union_type_t)UINT8_C(0))
#define mac_rslicing_SliceParams_static ((mac_rslicing_SliceParams_union_type_t)UINT8_C(1))
#define mac_rslicing_SliceParams_nvs ((mac_rslicing_SliceParams_union_type_t)UINT8_C(2))
#define mac_rslicing_SliceParams_scn19 ((mac_rslicing_SliceParams_union_type_t)UINT8_C(3))
#define mac_rslicing_SliceParams_edf ((mac_rslicing_SliceParams_union_type_t)UINT8_C(4))

static inline const char *mac_rslicing_SliceParams_type_name(mac_rslicing_SliceParams_union_type_t type)
{
    switch (type) {
    case mac_rslicing_SliceParams_NONE: return "NONE";
    case mac_rslicing_SliceParams_static: return "static";
    case mac_rslicing_SliceParams_nvs: return "nvs";
    case mac_rslicing_SliceParams_scn19: return "scn19";
    case mac_rslicing_SliceParams_edf: return "edf";
    default: return "";
    }
}

static inline int mac_rslicing_SliceParams_is_known_type(mac_rslicing_SliceParams_union_type_t type)
{
    switch (type) {
    case mac_rslicing_SliceParams_NONE: return 1;
    case mac_rslicing_SliceParams_static: return 1;
    case mac_rslicing_SliceParams_nvs: return 1;
    case mac_rslicing_SliceParams_scn19: return 1;
    case mac_rslicing_SliceParams_edf: return 1;
    default: return 0;
    }
}


struct mac_rslicing_Slice_table { uint8_t unused__; };

static inline size_t mac_rslicing_Slice_vec_len(mac_rslicing_Slice_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_Slice_table_t mac_rslicing_Slice_vec_at(mac_rslicing_Slice_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_Slice_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_Slice)

__flatbuffers_define_scalar_field(0, mac_rslicing_Slice, id, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_string_field(1, mac_rslicing_Slice, label, 0)
__flatbuffers_define_string_field(2, mac_rslicing_Slice, scheduler, 0)
__flatbuffers_define_union_field(flatbuffers_, 4, mac_rslicing_Slice, params, mac_rslicing_SliceParams, 0)

struct mac_rslicing_UlDlSliceConfig_table { uint8_t unused__; };

static inline size_t mac_rslicing_UlDlSliceConfig_vec_len(mac_rslicing_UlDlSliceConfig_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_UlDlSliceConfig_table_t mac_rslicing_UlDlSliceConfig_vec_at(mac_rslicing_UlDlSliceConfig_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_UlDlSliceConfig_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_UlDlSliceConfig)

__flatbuffers_define_scalar_field(0, mac_rslicing_UlDlSliceConfig, algorithm, mac_rslicing_SliceAlgorithm, mac_rslicing_SliceAlgorithm_enum_t, UINT8_C(0))
__flatbuffers_define_vector_field(1, mac_rslicing_UlDlSliceConfig, slices, mac_rslicing_Slice_vec_t, 0)
__flatbuffers_define_string_field(2, mac_rslicing_UlDlSliceConfig, scheduler, 0)

struct mac_rslicing_SliceConfig_table { uint8_t unused__; };

static inline size_t mac_rslicing_SliceConfig_vec_len(mac_rslicing_SliceConfig_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_SliceConfig_table_t mac_rslicing_SliceConfig_vec_at(mac_rslicing_SliceConfig_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_SliceConfig_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_SliceConfig)

__flatbuffers_define_table_field(0, mac_rslicing_SliceConfig, dl, mac_rslicing_UlDlSliceConfig_table_t, 0)
__flatbuffers_define_table_field(1, mac_rslicing_SliceConfig, ul, mac_rslicing_UlDlSliceConfig_table_t, 0)

struct mac_rslicing_UeSliceAssoc_table { uint8_t unused__; };

static inline size_t mac_rslicing_UeSliceAssoc_vec_len(mac_rslicing_UeSliceAssoc_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_UeSliceAssoc_table_t mac_rslicing_UeSliceAssoc_vec_at(mac_rslicing_UeSliceAssoc_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_UeSliceAssoc_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_UeSliceAssoc)

__flatbuffers_define_scalar_field(0, mac_rslicing_UeSliceAssoc, rnti, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(1, mac_rslicing_UeSliceAssoc, dlId, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, mac_rslicing_UeSliceAssoc, ulId, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct mac_rslicing_UeSliceConfig_table { uint8_t unused__; };

static inline size_t mac_rslicing_UeSliceConfig_vec_len(mac_rslicing_UeSliceConfig_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_UeSliceConfig_table_t mac_rslicing_UeSliceConfig_vec_at(mac_rslicing_UeSliceConfig_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_UeSliceConfig_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_UeSliceConfig)

__flatbuffers_define_vector_field(0, mac_rslicing_UeSliceConfig, ues, mac_rslicing_UeSliceAssoc_vec_t, 0)

struct mac_rslicing_DelSliceConfig_table { uint8_t unused__; };

static inline size_t mac_rslicing_DelSliceConfig_vec_len(mac_rslicing_DelSliceConfig_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_DelSliceConfig_table_t mac_rslicing_DelSliceConfig_vec_at(mac_rslicing_DelSliceConfig_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_DelSliceConfig_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_DelSliceConfig)

__flatbuffers_define_vector_field(0, mac_rslicing_DelSliceConfig, dl, flatbuffers_uint32_vec_t, 0)
__flatbuffers_define_vector_field(1, mac_rslicing_DelSliceConfig, ul, flatbuffers_uint32_vec_t, 0)

struct mac_rslicing_EventTrigger_table { uint8_t unused__; };

static inline size_t mac_rslicing_EventTrigger_vec_len(mac_rslicing_EventTrigger_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_EventTrigger_table_t mac_rslicing_EventTrigger_vec_at(mac_rslicing_EventTrigger_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_EventTrigger_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_EventTrigger)

__flatbuffers_define_scalar_field(0, mac_rslicing_EventTrigger, reportOccasion, mac_rslicing_ReportOccasion, mac_rslicing_ReportOccasion_enum_t, UINT8_C(0))

struct mac_rslicing_IndicationHeader_table { uint8_t unused__; };

static inline size_t mac_rslicing_IndicationHeader_vec_len(mac_rslicing_IndicationHeader_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_IndicationHeader_table_t mac_rslicing_IndicationHeader_vec_at(mac_rslicing_IndicationHeader_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_IndicationHeader_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_IndicationHeader)


struct mac_rslicing_IndicationMessage_table { uint8_t unused__; };

static inline size_t mac_rslicing_IndicationMessage_vec_len(mac_rslicing_IndicationMessage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_IndicationMessage_table_t mac_rslicing_IndicationMessage_vec_at(mac_rslicing_IndicationMessage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_IndicationMessage_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_IndicationMessage)

__flatbuffers_define_table_field(0, mac_rslicing_IndicationMessage, sliceConfig, mac_rslicing_SliceConfig_table_t, 0)
__flatbuffers_define_table_field(1, mac_rslicing_IndicationMessage, ueSliceConfig, mac_rslicing_UeSliceConfig_table_t, 0)

struct mac_rslicing_ControlHeader_table { uint8_t unused__; };

static inline size_t mac_rslicing_ControlHeader_vec_len(mac_rslicing_ControlHeader_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_ControlHeader_table_t mac_rslicing_ControlHeader_vec_at(mac_rslicing_ControlHeader_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_ControlHeader_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_ControlHeader)


struct mac_rslicing_AddModSliceCommand_table { uint8_t unused__; };

static inline size_t mac_rslicing_AddModSliceCommand_vec_len(mac_rslicing_AddModSliceCommand_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_AddModSliceCommand_table_t mac_rslicing_AddModSliceCommand_vec_at(mac_rslicing_AddModSliceCommand_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_AddModSliceCommand_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_AddModSliceCommand)

__flatbuffers_define_table_field(0, mac_rslicing_AddModSliceCommand, sliceConfig, mac_rslicing_SliceConfig_table_t, 0)

struct mac_rslicing_DelSliceCommand_table { uint8_t unused__; };

static inline size_t mac_rslicing_DelSliceCommand_vec_len(mac_rslicing_DelSliceCommand_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_DelSliceCommand_table_t mac_rslicing_DelSliceCommand_vec_at(mac_rslicing_DelSliceCommand_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_DelSliceCommand_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_DelSliceCommand)

__flatbuffers_define_table_field(0, mac_rslicing_DelSliceCommand, delSliceConfig, mac_rslicing_DelSliceConfig_table_t, 0)

struct mac_rslicing_UeSliceAssocCommand_table { uint8_t unused__; };

static inline size_t mac_rslicing_UeSliceAssocCommand_vec_len(mac_rslicing_UeSliceAssocCommand_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_UeSliceAssocCommand_table_t mac_rslicing_UeSliceAssocCommand_vec_at(mac_rslicing_UeSliceAssocCommand_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_UeSliceAssocCommand_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_UeSliceAssocCommand)

__flatbuffers_define_table_field(0, mac_rslicing_UeSliceAssocCommand, ueSliceConfig, mac_rslicing_UeSliceConfig_table_t, 0)
typedef uint8_t mac_rslicing_ControlCommand_union_type_t;
__flatbuffers_define_integer_type(mac_rslicing_ControlCommand, mac_rslicing_ControlCommand_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, mac_rslicing_ControlCommand)
#define mac_rslicing_ControlCommand_NONE ((mac_rslicing_ControlCommand_union_type_t)UINT8_C(0))
#define mac_rslicing_ControlCommand_addModSlice ((mac_rslicing_ControlCommand_union_type_t)UINT8_C(1))
#define mac_rslicing_ControlCommand_delSlice ((mac_rslicing_ControlCommand_union_type_t)UINT8_C(2))
#define mac_rslicing_ControlCommand_ueSliceAssoc ((mac_rslicing_ControlCommand_union_type_t)UINT8_C(3))

static inline const char *mac_rslicing_ControlCommand_type_name(mac_rslicing_ControlCommand_union_type_t type)
{
    switch (type) {
    case mac_rslicing_ControlCommand_NONE: return "NONE";
    case mac_rslicing_ControlCommand_addModSlice: return "addModSlice";
    case mac_rslicing_ControlCommand_delSlice: return "delSlice";
    case mac_rslicing_ControlCommand_ueSliceAssoc: return "ueSliceAssoc";
    default: return "";
    }
}

static inline int mac_rslicing_ControlCommand_is_known_type(mac_rslicing_ControlCommand_union_type_t type)
{
    switch (type) {
    case mac_rslicing_ControlCommand_NONE: return 1;
    case mac_rslicing_ControlCommand_addModSlice: return 1;
    case mac_rslicing_ControlCommand_delSlice: return 1;
    case mac_rslicing_ControlCommand_ueSliceAssoc: return 1;
    default: return 0;
    }
}


struct mac_rslicing_ControlMessage_table { uint8_t unused__; };

static inline size_t mac_rslicing_ControlMessage_vec_len(mac_rslicing_ControlMessage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_ControlMessage_table_t mac_rslicing_ControlMessage_vec_at(mac_rslicing_ControlMessage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_ControlMessage_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_ControlMessage)

__flatbuffers_define_union_field(flatbuffers_, 1, mac_rslicing_ControlMessage, command, mac_rslicing_ControlCommand, 0)

struct mac_rslicing_ControlOutcome_table { uint8_t unused__; };

static inline size_t mac_rslicing_ControlOutcome_vec_len(mac_rslicing_ControlOutcome_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_ControlOutcome_table_t mac_rslicing_ControlOutcome_vec_at(mac_rslicing_ControlOutcome_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_ControlOutcome_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_ControlOutcome)

__flatbuffers_define_string_field(0, mac_rslicing_ControlOutcome, diagnostic, 0)

struct mac_rslicing_CallProcessId_table { uint8_t unused__; };

static inline size_t mac_rslicing_CallProcessId_vec_len(mac_rslicing_CallProcessId_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_CallProcessId_table_t mac_rslicing_CallProcessId_vec_at(mac_rslicing_CallProcessId_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_CallProcessId_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_CallProcessId)

__flatbuffers_define_scalar_field(0, mac_rslicing_CallProcessId, id, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct mac_rslicing_SupportedAlgorithm_table { uint8_t unused__; };

static inline size_t mac_rslicing_SupportedAlgorithm_vec_len(mac_rslicing_SupportedAlgorithm_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_SupportedAlgorithm_table_t mac_rslicing_SupportedAlgorithm_vec_at(mac_rslicing_SupportedAlgorithm_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_SupportedAlgorithm_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_SupportedAlgorithm)

__flatbuffers_define_scalar_field(0, mac_rslicing_SupportedAlgorithm, algorithm, mac_rslicing_SliceAlgorithm, mac_rslicing_SliceAlgorithm_enum_t, UINT8_C(0))

struct mac_rslicing_RanFunctionDefinition_table { uint8_t unused__; };

static inline size_t mac_rslicing_RanFunctionDefinition_vec_len(mac_rslicing_RanFunctionDefinition_vec_t vec)
__flatbuffers_vec_len(vec)
static inline mac_rslicing_RanFunctionDefinition_table_t mac_rslicing_RanFunctionDefinition_vec_at(mac_rslicing_RanFunctionDefinition_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(mac_rslicing_RanFunctionDefinition_table_t, vec, i, 0)
__flatbuffers_table_as_root(mac_rslicing_RanFunctionDefinition)

__flatbuffers_define_vector_field(0, mac_rslicing_RanFunctionDefinition, supportedAlgorithms, mac_rslicing_SupportedAlgorithm_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* RSLICING_READER_H */
